// Code generated by MockGen. DO NOT EDIT.
// Source: contract.go
//
// Generated by this command:
//
//	mockgen -source=contract.go -destination=mock_update_test.go -package=update_test
//

// Package update_test is a generated GoMock package.
package update_test

import (
	context "context"
	reflect "reflect"
	time "time"

	model "github.com/khambek-archakov/jitLog/internal/model"
	dto "github.com/khambek-archakov/jitLog/internal/usecase/dto"
	gomock "go.uber.org/mock/gomock"
)

// Mocksender is a mock of sender interface.
type Mocksender struct {
	ctrl     *gomock.Controller
	recorder *MocksenderMockRecorder
	isgomock struct{}
}

// MocksenderMockRecorder is the mock recorder for Mocksender.
type MocksenderMockRecorder struct {
	mock *Mocksender
}

// NewMocksender creates a new mock instance.
func NewMocksender(ctrl *gomock.Controller) *Mocksender {
	mock := &Mocksender{ctrl: ctrl}
	mock.recorder = &MocksenderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mocksender) EXPECT() *MocksenderMockRecorder {
	return m.recorder
}

// AnswerCallback mocks base method.
func (m *Mocksender) AnswerCallback(ctx context.Context, callbackID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AnswerCallback", ctx, callbackID)
	ret0, _ := ret[0].(error)
	return ret0
}

// AnswerCallback indicates an expected call of AnswerCallback.
func (mr *MocksenderMockRecorder) AnswerCallback(ctx, callbackID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AnswerCallback", reflect.TypeOf((*Mocksender)(nil).AnswerCallback), ctx, callbackID)
}

// AnswerCallbackWithText mocks base method.
func (m *Mocksender) AnswerCallbackWithText(ctx context.Context, callbackID, text string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AnswerCallbackWithText", ctx, callbackID, text)
	ret0, _ := ret[0].(error)
	return ret0
}

// AnswerCallbackWithText indicates an expected call of AnswerCallbackWithText.
func (mr *MocksenderMockRecorder) AnswerCallbackWithText(ctx, callbackID, text any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AnswerCallbackWithText", reflect.TypeOf((*Mocksender)(nil).AnswerCallbackWithText), ctx, callbackID, text)
}

// EditMessageWithKeyboard mocks base method.
func (m *Mocksender) EditMessageWithKeyboard(ctx context.Context, chatID int64, messageID int, text string, keyboard dto.Keyboard) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EditMessageWithKeyboard", ctx, chatID, messageID, text, keyboard)
	ret0, _ := ret[0].(error)
	return ret0
}

// EditMessageWithKeyboard indicates an expected call of EditMessageWithKeyboard.
func (mr *MocksenderMockRecorder) EditMessageWithKeyboard(ctx, chatID, messageID, text, keyboard any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EditMessageWithKeyboard", reflect.TypeOf((*Mocksender)(nil).EditMessageWithKeyboard), ctx, chatID, messageID, text, keyboard)
}

// Send mocks base method.
func (m *Mocksender) Send(ctx context.Context, chatID int64, text string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Send", ctx, chatID, text)
	ret0, _ := ret[0].(error)
	return ret0
}

// Send indicates an expected call of Send.
func (mr *MocksenderMockRecorder) Send(ctx, chatID, text any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Send", reflect.TypeOf((*Mocksender)(nil).Send), ctx, chatID, text)
}

// SendWithKeyboard mocks base method.
func (m *Mocksender) SendWithKeyboard(ctx context.Context, chatID int64, text string, keyboard dto.Keyboard) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendWithKeyboard", ctx, chatID, text, keyboard)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendWithKeyboard indicates an expected call of SendWithKeyboard.
func (mr *MocksenderMockRecorder) SendWithKeyboard(ctx, chatID, text, keyboard any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendWithKeyboard", reflect.TypeOf((*Mocksender)(nil).SendWithKeyboard), ctx, chatID, text, keyboard)
}

// MockcompetitionRepo is a mock of competitionRepo interface.
type MockcompetitionRepo struct {
	ctrl     *gomock.Controller
	recorder *MockcompetitionRepoMockRecorder
	isgomock struct{}
}

// MockcompetitionRepoMockRecorder is the mock recorder for MockcompetitionRepo.
type MockcompetitionRepoMockRecorder struct {
	mock *MockcompetitionRepo
}

// NewMockcompetitionRepo creates a new mock instance.
func NewMockcompetitionRepo(ctrl *gomock.Controller) *MockcompetitionRepo {
	mock := &MockcompetitionRepo{ctrl: ctrl}
	mock.recorder = &MockcompetitionRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockcompetitionRepo) EXPECT() *MockcompetitionRepoMockRecorder {
	return m.recorder
}

// DeleteEditDraft mocks base method.
func (m *MockcompetitionRepo) DeleteEditDraft(ctx context.Context, userID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteEditDraft", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteEditDraft indicates an expected call of DeleteEditDraft.
func (mr *MockcompetitionRepoMockRecorder) DeleteEditDraft(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteEditDraft", reflect.TypeOf((*MockcompetitionRepo)(nil).DeleteEditDraft), ctx, userID)
}

// GetUserCompetition mocks base method.
func (m *MockcompetitionRepo) GetUserCompetition(ctx context.Context, id int64) (*model.UserCompetition, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserCompetition", ctx, id)
	ret0, _ := ret[0].(*model.UserCompetition)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserCompetition indicates an expected call of GetUserCompetition.
func (mr *MockcompetitionRepoMockRecorder) GetUserCompetition(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserCompetition", reflect.TypeOf((*MockcompetitionRepo)(nil).GetUserCompetition), ctx, id)
}

// SetEditDraft mocks base method.
func (m *MockcompetitionRepo) SetEditDraft(ctx context.Context, userID, userCompetitionID int64, field model.UserCompetitionEditField) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetEditDraft", ctx, userID, userCompetitionID, field)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetEditDraft indicates an expected call of SetEditDraft.
func (mr *MockcompetitionRepoMockRecorder) SetEditDraft(ctx, userID, userCompetitionID, field any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetEditDraft", reflect.TypeOf((*MockcompetitionRepo)(nil).SetEditDraft), ctx, userID, userCompetitionID, field)
}

// UpdateUserCompetition mocks base method.
func (m *MockcompetitionRepo) UpdateUserCompetition(ctx context.Context, id int64, title string, date time.Time, endDate *time.Time, city, url, result *string) (*model.UserCompetition, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUserCompetition", ctx, id, title, date, endDate, city, url, result)
	ret0, _ := ret[0].(*model.UserCompetition)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateUserCompetition indicates an expected call of UpdateUserCompetition.
func (mr *MockcompetitionRepoMockRecorder) UpdateUserCompetition(ctx, id, title, date, endDate, city, url, result any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUserCompetition", reflect.TypeOf((*MockcompetitionRepo)(nil).UpdateUserCompetition), ctx, id, title, date, endDate, city, url, result)
}
