// Code generated by MockGen. DO NOT EDIT.
// Source: contract.go
//
// Generated by this command:
//
//	mockgen -source=contract.go -destination=mock_steps_test.go -package=steps_test
//

// Package steps_test is a generated GoMock package.
package steps_test

import (
	context "context"
	reflect "reflect"
	time "time"

	model "github.com/khambek-archakov/jitLog/internal/model"
	dto "github.com/khambek-archakov/jitLog/internal/usecase/dto"
	gomock "go.uber.org/mock/gomock"
)

// Mocksender is a mock of sender interface.
type Mocksender struct {
	ctrl     *gomock.Controller
	recorder *MocksenderMockRecorder
	isgomock struct{}
}

// MocksenderMockRecorder is the mock recorder for Mocksender.
type MocksenderMockRecorder struct {
	mock *Mocksender
}

// NewMocksender creates a new mock instance.
func NewMocksender(ctrl *gomock.Controller) *Mocksender {
	mock := &Mocksender{ctrl: ctrl}
	mock.recorder = &MocksenderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mocksender) EXPECT() *MocksenderMockRecorder {
	return m.recorder
}

// AnswerCallback mocks base method.
func (m *Mocksender) AnswerCallback(ctx context.Context, callbackID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AnswerCallback", ctx, callbackID)
	ret0, _ := ret[0].(error)
	return ret0
}

// AnswerCallback indicates an expected call of AnswerCallback.
func (mr *MocksenderMockRecorder) AnswerCallback(ctx, callbackID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AnswerCallback", reflect.TypeOf((*Mocksender)(nil).AnswerCallback), ctx, callbackID)
}

// AnswerCallbackWithText mocks base method.
func (m *Mocksender) AnswerCallbackWithText(ctx context.Context, callbackID, text string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AnswerCallbackWithText", ctx, callbackID, text)
	ret0, _ := ret[0].(error)
	return ret0
}

// AnswerCallbackWithText indicates an expected call of AnswerCallbackWithText.
func (mr *MocksenderMockRecorder) AnswerCallbackWithText(ctx, callbackID, text any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AnswerCallbackWithText", reflect.TypeOf((*Mocksender)(nil).AnswerCallbackWithText), ctx, callbackID, text)
}

// EditMessageWithKeyboard mocks base method.
func (m *Mocksender) EditMessageWithKeyboard(ctx context.Context, chatID int64, messageID int, text string, keyboard dto.Keyboard) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EditMessageWithKeyboard", ctx, chatID, messageID, text, keyboard)
	ret0, _ := ret[0].(error)
	return ret0
}

// EditMessageWithKeyboard indicates an expected call of EditMessageWithKeyboard.
func (mr *MocksenderMockRecorder) EditMessageWithKeyboard(ctx, chatID, messageID, text, keyboard any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EditMessageWithKeyboard", reflect.TypeOf((*Mocksender)(nil).EditMessageWithKeyboard), ctx, chatID, messageID, text, keyboard)
}

// Send mocks base method.
func (m *Mocksender) Send(ctx context.Context, chatID int64, text string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Send", ctx, chatID, text)
	ret0, _ := ret[0].(error)
	return ret0
}

// Send indicates an expected call of Send.
func (mr *MocksenderMockRecorder) Send(ctx, chatID, text any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Send", reflect.TypeOf((*Mocksender)(nil).Send), ctx, chatID, text)
}

// SendWithKeyboard mocks base method.
func (m *Mocksender) SendWithKeyboard(ctx context.Context, chatID int64, text string, keyboard dto.Keyboard) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendWithKeyboard", ctx, chatID, text, keyboard)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendWithKeyboard indicates an expected call of SendWithKeyboard.
func (mr *MocksenderMockRecorder) SendWithKeyboard(ctx, chatID, text, keyboard any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendWithKeyboard", reflect.TypeOf((*Mocksender)(nil).SendWithKeyboard), ctx, chatID, text, keyboard)
}

// MockdraftRepo is a mock of draftRepo interface.
type MockdraftRepo struct {
	ctrl     *gomock.Controller
	recorder *MockdraftRepoMockRecorder
	isgomock struct{}
}

// MockdraftRepoMockRecorder is the mock recorder for MockdraftRepo.
type MockdraftRepoMockRecorder struct {
	mock *MockdraftRepo
}

// NewMockdraftRepo creates a new mock instance.
func NewMockdraftRepo(ctrl *gomock.Controller) *MockdraftRepo {
	mock := &MockdraftRepo{ctrl: ctrl}
	mock.recorder = &MockdraftRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockdraftRepo) EXPECT() *MockdraftRepoMockRecorder {
	return m.recorder
}

// CreateUserCompetition mocks base method.
func (m *MockdraftRepo) CreateUserCompetition(ctx context.Context, userID int64, title string, date time.Time) (*model.UserCompetition, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUserCompetition", ctx, userID, title, date)
	ret0, _ := ret[0].(*model.UserCompetition)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateUserCompetition indicates an expected call of CreateUserCompetition.
func (mr *MockdraftRepoMockRecorder) CreateUserCompetition(ctx, userID, title, date any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUserCompetition", reflect.TypeOf((*MockdraftRepo)(nil).CreateUserCompetition), ctx, userID, title, date)
}

// DeleteDraft mocks base method.
func (m *MockdraftRepo) DeleteDraft(ctx context.Context, userID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteDraft", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteDraft indicates an expected call of DeleteDraft.
func (mr *MockdraftRepoMockRecorder) DeleteDraft(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteDraft", reflect.TypeOf((*MockdraftRepo)(nil).DeleteDraft), ctx, userID)
}

// UpdateDraft mocks base method.
func (m *MockdraftRepo) UpdateDraft(ctx context.Context, d *model.UserCompetitionDraft) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateDraft", ctx, d)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateDraft indicates an expected call of UpdateDraft.
func (mr *MockdraftRepoMockRecorder) UpdateDraft(ctx, d any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateDraft", reflect.TypeOf((*MockdraftRepo)(nil).UpdateDraft), ctx, d)
}
