// Code generated by MockGen. DO NOT EDIT.
// Source: contract.go
//
// Generated by this command:
//
//	mockgen -source=contract.go -destination=mock_router_test.go -package=router_test
//

// Package router_test is a generated GoMock package.
package router_test

import (
	context "context"
	reflect "reflect"

	model "github.com/khambek-archakov/jitLog/internal/model"
	dto "github.com/khambek-archakov/jitLog/internal/usecase/onboarding/dto"
	gomock "go.uber.org/mock/gomock"
)

// Mockonboarding is a mock of onboarding interface.
type Mockonboarding struct {
	ctrl     *gomock.Controller
	recorder *MockonboardingMockRecorder
	isgomock struct{}
}

// MockonboardingMockRecorder is the mock recorder for Mockonboarding.
type MockonboardingMockRecorder struct {
	mock *Mockonboarding
}

// NewMockonboarding creates a new mock instance.
func NewMockonboarding(ctrl *gomock.Controller) *Mockonboarding {
	mock := &Mockonboarding{ctrl: ctrl}
	mock.recorder = &MockonboardingMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mockonboarding) EXPECT() *MockonboardingMockRecorder {
	return m.recorder
}

// Handle mocks base method.
func (m *Mockonboarding) Handle(ctx context.Context, u *model.User, in dto.Input) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Handle", ctx, u, in)
	ret0, _ := ret[0].(error)
	return ret0
}

// Handle indicates an expected call of Handle.
func (mr *MockonboardingMockRecorder) Handle(ctx, u, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Handle", reflect.TypeOf((*Mockonboarding)(nil).Handle), ctx, u, in)
}

// MocktrainingCreate is a mock of trainingCreate interface.
type MocktrainingCreate struct {
	ctrl     *gomock.Controller
	recorder *MocktrainingCreateMockRecorder
	isgomock struct{}
}

// MocktrainingCreateMockRecorder is the mock recorder for MocktrainingCreate.
type MocktrainingCreateMockRecorder struct {
	mock *MocktrainingCreate
}

// NewMocktrainingCreate creates a new mock instance.
func NewMocktrainingCreate(ctrl *gomock.Controller) *MocktrainingCreate {
	mock := &MocktrainingCreate{ctrl: ctrl}
	mock.recorder = &MocktrainingCreateMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocktrainingCreate) EXPECT() *MocktrainingCreateMockRecorder {
	return m.recorder
}

// Begin mocks base method.
func (m *MocktrainingCreate) Begin(ctx context.Context, userID int64, in dto.Input) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Begin", ctx, userID, in)
	ret0, _ := ret[0].(error)
	return ret0
}

// Begin indicates an expected call of Begin.
func (mr *MocktrainingCreateMockRecorder) Begin(ctx, userID, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Begin", reflect.TypeOf((*MocktrainingCreate)(nil).Begin), ctx, userID, in)
}

// Continue mocks base method.
func (m *MocktrainingCreate) Continue(ctx context.Context, d *model.TrainingDraft, in dto.Input) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Continue", ctx, d, in)
	ret0, _ := ret[0].(error)
	return ret0
}

// Continue indicates an expected call of Continue.
func (mr *MocktrainingCreateMockRecorder) Continue(ctx, d, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Continue", reflect.TypeOf((*MocktrainingCreate)(nil).Continue), ctx, d, in)
}

// MocktrainingInfo is a mock of trainingInfo interface.
type MocktrainingInfo struct {
	ctrl     *gomock.Controller
	recorder *MocktrainingInfoMockRecorder
	isgomock struct{}
}

// MocktrainingInfoMockRecorder is the mock recorder for MocktrainingInfo.
type MocktrainingInfoMockRecorder struct {
	mock *MocktrainingInfo
}

// NewMocktrainingInfo creates a new mock instance.
func NewMocktrainingInfo(ctrl *gomock.Controller) *MocktrainingInfo {
	mock := &MocktrainingInfo{ctrl: ctrl}
	mock.recorder = &MocktrainingInfoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocktrainingInfo) EXPECT() *MocktrainingInfoMockRecorder {
	return m.recorder
}

// Handle mocks base method.
func (m *MocktrainingInfo) Handle(ctx context.Context, userID int64, in dto.Input) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Handle", ctx, userID, in)
	ret0, _ := ret[0].(error)
	return ret0
}

// Handle indicates an expected call of Handle.
func (mr *MocktrainingInfoMockRecorder) Handle(ctx, userID, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Handle", reflect.TypeOf((*MocktrainingInfo)(nil).Handle), ctx, userID, in)
}

// MocktrainingHistory is a mock of trainingHistory interface.
type MocktrainingHistory struct {
	ctrl     *gomock.Controller
	recorder *MocktrainingHistoryMockRecorder
	isgomock struct{}
}

// MocktrainingHistoryMockRecorder is the mock recorder for MocktrainingHistory.
type MocktrainingHistoryMockRecorder struct {
	mock *MocktrainingHistory
}

// NewMocktrainingHistory creates a new mock instance.
func NewMocktrainingHistory(ctrl *gomock.Controller) *MocktrainingHistory {
	mock := &MocktrainingHistory{ctrl: ctrl}
	mock.recorder = &MocktrainingHistoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocktrainingHistory) EXPECT() *MocktrainingHistoryMockRecorder {
	return m.recorder
}

// Handle mocks base method.
func (m *MocktrainingHistory) Handle(ctx context.Context, userID int64, in dto.Input) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Handle", ctx, userID, in)
	ret0, _ := ret[0].(error)
	return ret0
}

// Handle indicates an expected call of Handle.
func (mr *MocktrainingHistoryMockRecorder) Handle(ctx, userID, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Handle", reflect.TypeOf((*MocktrainingHistory)(nil).Handle), ctx, userID, in)
}

// MocktrainingUpdate is a mock of trainingUpdate interface.
type MocktrainingUpdate struct {
	ctrl     *gomock.Controller
	recorder *MocktrainingUpdateMockRecorder
	isgomock struct{}
}

// MocktrainingUpdateMockRecorder is the mock recorder for MocktrainingUpdate.
type MocktrainingUpdateMockRecorder struct {
	mock *MocktrainingUpdate
}

// NewMocktrainingUpdate creates a new mock instance.
func NewMocktrainingUpdate(ctrl *gomock.Controller) *MocktrainingUpdate {
	mock := &MocktrainingUpdate{ctrl: ctrl}
	mock.recorder = &MocktrainingUpdateMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocktrainingUpdate) EXPECT() *MocktrainingUpdateMockRecorder {
	return m.recorder
}

// Continue mocks base method.
func (m *MocktrainingUpdate) Continue(ctx context.Context, d *model.TrainingEditDraft, in dto.Input) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Continue", ctx, d, in)
	ret0, _ := ret[0].(error)
	return ret0
}

// Continue indicates an expected call of Continue.
func (mr *MocktrainingUpdateMockRecorder) Continue(ctx, d, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Continue", reflect.TypeOf((*MocktrainingUpdate)(nil).Continue), ctx, d, in)
}

// Handle mocks base method.
func (m *MocktrainingUpdate) Handle(ctx context.Context, userID int64, in dto.Input) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Handle", ctx, userID, in)
	ret0, _ := ret[0].(error)
	return ret0
}

// Handle indicates an expected call of Handle.
func (mr *MocktrainingUpdateMockRecorder) Handle(ctx, userID, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Handle", reflect.TypeOf((*MocktrainingUpdate)(nil).Handle), ctx, userID, in)
}

// MocktrainingDelete is a mock of trainingDelete interface.
type MocktrainingDelete struct {
	ctrl     *gomock.Controller
	recorder *MocktrainingDeleteMockRecorder
	isgomock struct{}
}

// MocktrainingDeleteMockRecorder is the mock recorder for MocktrainingDelete.
type MocktrainingDeleteMockRecorder struct {
	mock *MocktrainingDelete
}

// NewMocktrainingDelete creates a new mock instance.
func NewMocktrainingDelete(ctrl *gomock.Controller) *MocktrainingDelete {
	mock := &MocktrainingDelete{ctrl: ctrl}
	mock.recorder = &MocktrainingDeleteMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocktrainingDelete) EXPECT() *MocktrainingDeleteMockRecorder {
	return m.recorder
}

// Handle mocks base method.
func (m *MocktrainingDelete) Handle(ctx context.Context, userID int64, in dto.Input) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Handle", ctx, userID, in)
	ret0, _ := ret[0].(error)
	return ret0
}

// Handle indicates an expected call of Handle.
func (mr *MocktrainingDeleteMockRecorder) Handle(ctx, userID, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Handle", reflect.TypeOf((*MocktrainingDelete)(nil).Handle), ctx, userID, in)
}

// Mockuser is a mock of user interface.
type Mockuser struct {
	ctrl     *gomock.Controller
	recorder *MockuserMockRecorder
	isgomock struct{}
}

// MockuserMockRecorder is the mock recorder for Mockuser.
type MockuserMockRecorder struct {
	mock *Mockuser
}

// NewMockuser creates a new mock instance.
func NewMockuser(ctrl *gomock.Controller) *Mockuser {
	mock := &Mockuser{ctrl: ctrl}
	mock.recorder = &MockuserMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mockuser) EXPECT() *MockuserMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *Mockuser) Create(ctx context.Context, telegramID int64) (*model.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, telegramID)
	ret0, _ := ret[0].(*model.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockuserMockRecorder) Create(ctx, telegramID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*Mockuser)(nil).Create), ctx, telegramID)
}

// GetByTelegramID mocks base method.
func (m *Mockuser) GetByTelegramID(ctx context.Context, telegramID int64) (*model.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByTelegramID", ctx, telegramID)
	ret0, _ := ret[0].(*model.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByTelegramID indicates an expected call of GetByTelegramID.
func (mr *MockuserMockRecorder) GetByTelegramID(ctx, telegramID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByTelegramID", reflect.TypeOf((*Mockuser)(nil).GetByTelegramID), ctx, telegramID)
}

// MocktrainingDraft is a mock of trainingDraft interface.
type MocktrainingDraft struct {
	ctrl     *gomock.Controller
	recorder *MocktrainingDraftMockRecorder
	isgomock struct{}
}

// MocktrainingDraftMockRecorder is the mock recorder for MocktrainingDraft.
type MocktrainingDraftMockRecorder struct {
	mock *MocktrainingDraft
}

// NewMocktrainingDraft creates a new mock instance.
func NewMocktrainingDraft(ctrl *gomock.Controller) *MocktrainingDraft {
	mock := &MocktrainingDraft{ctrl: ctrl}
	mock.recorder = &MocktrainingDraftMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocktrainingDraft) EXPECT() *MocktrainingDraftMockRecorder {
	return m.recorder
}

// GetDraftByUserID mocks base method.
func (m *MocktrainingDraft) GetDraftByUserID(ctx context.Context, userID int64) (*model.TrainingDraft, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDraftByUserID", ctx, userID)
	ret0, _ := ret[0].(*model.TrainingDraft)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDraftByUserID indicates an expected call of GetDraftByUserID.
func (mr *MocktrainingDraftMockRecorder) GetDraftByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDraftByUserID", reflect.TypeOf((*MocktrainingDraft)(nil).GetDraftByUserID), ctx, userID)
}

// MocktrainingEditDraft is a mock of trainingEditDraft interface.
type MocktrainingEditDraft struct {
	ctrl     *gomock.Controller
	recorder *MocktrainingEditDraftMockRecorder
	isgomock struct{}
}

// MocktrainingEditDraftMockRecorder is the mock recorder for MocktrainingEditDraft.
type MocktrainingEditDraftMockRecorder struct {
	mock *MocktrainingEditDraft
}

// NewMocktrainingEditDraft creates a new mock instance.
func NewMocktrainingEditDraft(ctrl *gomock.Controller) *MocktrainingEditDraft {
	mock := &MocktrainingEditDraft{ctrl: ctrl}
	mock.recorder = &MocktrainingEditDraftMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocktrainingEditDraft) EXPECT() *MocktrainingEditDraftMockRecorder {
	return m.recorder
}

// GetEditDraftByUserID mocks base method.
func (m *MocktrainingEditDraft) GetEditDraftByUserID(ctx context.Context, userID int64) (*model.TrainingEditDraft, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEditDraftByUserID", ctx, userID)
	ret0, _ := ret[0].(*model.TrainingEditDraft)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEditDraftByUserID indicates an expected call of GetEditDraftByUserID.
func (mr *MocktrainingEditDraftMockRecorder) GetEditDraftByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEditDraftByUserID", reflect.TypeOf((*MocktrainingEditDraft)(nil).GetEditDraftByUserID), ctx, userID)
}
