// Code generated by MockGen. DO NOT EDIT.
// Source: contract.go
//
// Generated by this command:
//
//	mockgen -source=contract.go -destination=mock_chain_test.go -package=chain_test
//

// Package chain_test is a generated GoMock package.
package chain_test

import (
	context "context"
	reflect "reflect"

	model "github.com/khambek-archakov/jitLog/internal/model"
	dto "github.com/khambek-archakov/jitLog/internal/usecase/dto"
	gomock "go.uber.org/mock/gomock"
)

// Mockonboarding is a mock of onboarding interface.
type Mockonboarding struct {
	ctrl     *gomock.Controller
	recorder *MockonboardingMockRecorder
	isgomock struct{}
}

// MockonboardingMockRecorder is the mock recorder for Mockonboarding.
type MockonboardingMockRecorder struct {
	mock *Mockonboarding
}

// NewMockonboarding creates a new mock instance.
func NewMockonboarding(ctrl *gomock.Controller) *Mockonboarding {
	mock := &Mockonboarding{ctrl: ctrl}
	mock.recorder = &MockonboardingMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mockonboarding) EXPECT() *MockonboardingMockRecorder {
	return m.recorder
}

// Handle mocks base method.
func (m *Mockonboarding) Handle(ctx context.Context, u *model.User, in dto.Input) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Handle", ctx, u, in)
	ret0, _ := ret[0].(error)
	return ret0
}

// Handle indicates an expected call of Handle.
func (mr *MockonboardingMockRecorder) Handle(ctx, u, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Handle", reflect.TypeOf((*Mockonboarding)(nil).Handle), ctx, u, in)
}

// MocktrainingCreate is a mock of trainingCreate interface.
type MocktrainingCreate struct {
	ctrl     *gomock.Controller
	recorder *MocktrainingCreateMockRecorder
	isgomock struct{}
}

// MocktrainingCreateMockRecorder is the mock recorder for MocktrainingCreate.
type MocktrainingCreateMockRecorder struct {
	mock *MocktrainingCreate
}

// NewMocktrainingCreate creates a new mock instance.
func NewMocktrainingCreate(ctrl *gomock.Controller) *MocktrainingCreate {
	mock := &MocktrainingCreate{ctrl: ctrl}
	mock.recorder = &MocktrainingCreateMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocktrainingCreate) EXPECT() *MocktrainingCreateMockRecorder {
	return m.recorder
}

// Begin mocks base method.
func (m *MocktrainingCreate) Begin(ctx context.Context, userID int64, in dto.Input) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Begin", ctx, userID, in)
	ret0, _ := ret[0].(error)
	return ret0
}

// Begin indicates an expected call of Begin.
func (mr *MocktrainingCreateMockRecorder) Begin(ctx, userID, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Begin", reflect.TypeOf((*MocktrainingCreate)(nil).Begin), ctx, userID, in)
}

// Continue mocks base method.
func (m *MocktrainingCreate) Continue(ctx context.Context, d *model.TrainingDraft, in dto.Input) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Continue", ctx, d, in)
	ret0, _ := ret[0].(error)
	return ret0
}

// Continue indicates an expected call of Continue.
func (mr *MocktrainingCreateMockRecorder) Continue(ctx, d, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Continue", reflect.TypeOf((*MocktrainingCreate)(nil).Continue), ctx, d, in)
}

// MocktrainingInfo is a mock of trainingInfo interface.
type MocktrainingInfo struct {
	ctrl     *gomock.Controller
	recorder *MocktrainingInfoMockRecorder
	isgomock struct{}
}

// MocktrainingInfoMockRecorder is the mock recorder for MocktrainingInfo.
type MocktrainingInfoMockRecorder struct {
	mock *MocktrainingInfo
}

// NewMocktrainingInfo creates a new mock instance.
func NewMocktrainingInfo(ctrl *gomock.Controller) *MocktrainingInfo {
	mock := &MocktrainingInfo{ctrl: ctrl}
	mock.recorder = &MocktrainingInfoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocktrainingInfo) EXPECT() *MocktrainingInfoMockRecorder {
	return m.recorder
}

// Handle mocks base method.
func (m *MocktrainingInfo) Handle(ctx context.Context, userID int64, in dto.Input) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Handle", ctx, userID, in)
	ret0, _ := ret[0].(error)
	return ret0
}

// Handle indicates an expected call of Handle.
func (mr *MocktrainingInfoMockRecorder) Handle(ctx, userID, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Handle", reflect.TypeOf((*MocktrainingInfo)(nil).Handle), ctx, userID, in)
}

// MocktrainingHistory is a mock of trainingHistory interface.
type MocktrainingHistory struct {
	ctrl     *gomock.Controller
	recorder *MocktrainingHistoryMockRecorder
	isgomock struct{}
}

// MocktrainingHistoryMockRecorder is the mock recorder for MocktrainingHistory.
type MocktrainingHistoryMockRecorder struct {
	mock *MocktrainingHistory
}

// NewMocktrainingHistory creates a new mock instance.
func NewMocktrainingHistory(ctrl *gomock.Controller) *MocktrainingHistory {
	mock := &MocktrainingHistory{ctrl: ctrl}
	mock.recorder = &MocktrainingHistoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocktrainingHistory) EXPECT() *MocktrainingHistoryMockRecorder {
	return m.recorder
}

// Handle mocks base method.
func (m *MocktrainingHistory) Handle(ctx context.Context, userID int64, in dto.Input) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Handle", ctx, userID, in)
	ret0, _ := ret[0].(error)
	return ret0
}

// Handle indicates an expected call of Handle.
func (mr *MocktrainingHistoryMockRecorder) Handle(ctx, userID, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Handle", reflect.TypeOf((*MocktrainingHistory)(nil).Handle), ctx, userID, in)
}

// MocktrainingUpdate is a mock of trainingUpdate interface.
type MocktrainingUpdate struct {
	ctrl     *gomock.Controller
	recorder *MocktrainingUpdateMockRecorder
	isgomock struct{}
}

// MocktrainingUpdateMockRecorder is the mock recorder for MocktrainingUpdate.
type MocktrainingUpdateMockRecorder struct {
	mock *MocktrainingUpdate
}

// NewMocktrainingUpdate creates a new mock instance.
func NewMocktrainingUpdate(ctrl *gomock.Controller) *MocktrainingUpdate {
	mock := &MocktrainingUpdate{ctrl: ctrl}
	mock.recorder = &MocktrainingUpdateMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocktrainingUpdate) EXPECT() *MocktrainingUpdateMockRecorder {
	return m.recorder
}

// Continue mocks base method.
func (m *MocktrainingUpdate) Continue(ctx context.Context, d *model.TrainingEditDraft, in dto.Input) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Continue", ctx, d, in)
	ret0, _ := ret[0].(error)
	return ret0
}

// Continue indicates an expected call of Continue.
func (mr *MocktrainingUpdateMockRecorder) Continue(ctx, d, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Continue", reflect.TypeOf((*MocktrainingUpdate)(nil).Continue), ctx, d, in)
}

// Handle mocks base method.
func (m *MocktrainingUpdate) Handle(ctx context.Context, userID int64, in dto.Input) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Handle", ctx, userID, in)
	ret0, _ := ret[0].(error)
	return ret0
}

// Handle indicates an expected call of Handle.
func (mr *MocktrainingUpdateMockRecorder) Handle(ctx, userID, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Handle", reflect.TypeOf((*MocktrainingUpdate)(nil).Handle), ctx, userID, in)
}

// MocktrainingDelete is a mock of trainingDelete interface.
type MocktrainingDelete struct {
	ctrl     *gomock.Controller
	recorder *MocktrainingDeleteMockRecorder
	isgomock struct{}
}

// MocktrainingDeleteMockRecorder is the mock recorder for MocktrainingDelete.
type MocktrainingDeleteMockRecorder struct {
	mock *MocktrainingDelete
}

// NewMocktrainingDelete creates a new mock instance.
func NewMocktrainingDelete(ctrl *gomock.Controller) *MocktrainingDelete {
	mock := &MocktrainingDelete{ctrl: ctrl}
	mock.recorder = &MocktrainingDeleteMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocktrainingDelete) EXPECT() *MocktrainingDeleteMockRecorder {
	return m.recorder
}

// Handle mocks base method.
func (m *MocktrainingDelete) Handle(ctx context.Context, userID int64, in dto.Input) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Handle", ctx, userID, in)
	ret0, _ := ret[0].(error)
	return ret0
}

// Handle indicates an expected call of Handle.
func (mr *MocktrainingDeleteMockRecorder) Handle(ctx, userID, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Handle", reflect.TypeOf((*MocktrainingDelete)(nil).Handle), ctx, userID, in)
}

// MocktrainingStats is a mock of trainingStats interface.
type MocktrainingStats struct {
	ctrl     *gomock.Controller
	recorder *MocktrainingStatsMockRecorder
	isgomock struct{}
}

// MocktrainingStatsMockRecorder is the mock recorder for MocktrainingStats.
type MocktrainingStatsMockRecorder struct {
	mock *MocktrainingStats
}

// NewMocktrainingStats creates a new mock instance.
func NewMocktrainingStats(ctrl *gomock.Controller) *MocktrainingStats {
	mock := &MocktrainingStats{ctrl: ctrl}
	mock.recorder = &MocktrainingStatsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocktrainingStats) EXPECT() *MocktrainingStatsMockRecorder {
	return m.recorder
}

// Handle mocks base method.
func (m *MocktrainingStats) Handle(ctx context.Context, userID int64, in dto.Input) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Handle", ctx, userID, in)
	ret0, _ := ret[0].(error)
	return ret0
}

// Handle indicates an expected call of Handle.
func (mr *MocktrainingStatsMockRecorder) Handle(ctx, userID, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Handle", reflect.TypeOf((*MocktrainingStats)(nil).Handle), ctx, userID, in)
}

// Mockprofile is a mock of profile interface.
type Mockprofile struct {
	ctrl     *gomock.Controller
	recorder *MockprofileMockRecorder
	isgomock struct{}
}

// MockprofileMockRecorder is the mock recorder for Mockprofile.
type MockprofileMockRecorder struct {
	mock *Mockprofile
}

// NewMockprofile creates a new mock instance.
func NewMockprofile(ctrl *gomock.Controller) *Mockprofile {
	mock := &Mockprofile{ctrl: ctrl}
	mock.recorder = &MockprofileMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mockprofile) EXPECT() *MockprofileMockRecorder {
	return m.recorder
}

// Continue mocks base method.
func (m *Mockprofile) Continue(ctx context.Context, u *model.User, d *model.ProfileEditDraft, in dto.Input) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Continue", ctx, u, d, in)
	ret0, _ := ret[0].(error)
	return ret0
}

// Continue indicates an expected call of Continue.
func (mr *MockprofileMockRecorder) Continue(ctx, u, d, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Continue", reflect.TypeOf((*Mockprofile)(nil).Continue), ctx, u, d, in)
}

// Handle mocks base method.
func (m *Mockprofile) Handle(ctx context.Context, u *model.User, in dto.Input) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Handle", ctx, u, in)
	ret0, _ := ret[0].(error)
	return ret0
}

// Handle indicates an expected call of Handle.
func (mr *MockprofileMockRecorder) Handle(ctx, u, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Handle", reflect.TypeOf((*Mockprofile)(nil).Handle), ctx, u, in)
}

// MockscheduleCreate is a mock of scheduleCreate interface.
type MockscheduleCreate struct {
	ctrl     *gomock.Controller
	recorder *MockscheduleCreateMockRecorder
	isgomock struct{}
}

// MockscheduleCreateMockRecorder is the mock recorder for MockscheduleCreate.
type MockscheduleCreateMockRecorder struct {
	mock *MockscheduleCreate
}

// NewMockscheduleCreate creates a new mock instance.
func NewMockscheduleCreate(ctrl *gomock.Controller) *MockscheduleCreate {
	mock := &MockscheduleCreate{ctrl: ctrl}
	mock.recorder = &MockscheduleCreateMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockscheduleCreate) EXPECT() *MockscheduleCreateMockRecorder {
	return m.recorder
}

// Begin mocks base method.
func (m *MockscheduleCreate) Begin(ctx context.Context, userID int64, in dto.Input) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Begin", ctx, userID, in)
	ret0, _ := ret[0].(error)
	return ret0
}

// Begin indicates an expected call of Begin.
func (mr *MockscheduleCreateMockRecorder) Begin(ctx, userID, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Begin", reflect.TypeOf((*MockscheduleCreate)(nil).Begin), ctx, userID, in)
}

// Continue mocks base method.
func (m *MockscheduleCreate) Continue(ctx context.Context, d *model.ScheduleDraft, in dto.Input) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Continue", ctx, d, in)
	ret0, _ := ret[0].(error)
	return ret0
}

// Continue indicates an expected call of Continue.
func (mr *MockscheduleCreateMockRecorder) Continue(ctx, d, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Continue", reflect.TypeOf((*MockscheduleCreate)(nil).Continue), ctx, d, in)
}

// MockscheduleList is a mock of scheduleList interface.
type MockscheduleList struct {
	ctrl     *gomock.Controller
	recorder *MockscheduleListMockRecorder
	isgomock struct{}
}

// MockscheduleListMockRecorder is the mock recorder for MockscheduleList.
type MockscheduleListMockRecorder struct {
	mock *MockscheduleList
}

// NewMockscheduleList creates a new mock instance.
func NewMockscheduleList(ctrl *gomock.Controller) *MockscheduleList {
	mock := &MockscheduleList{ctrl: ctrl}
	mock.recorder = &MockscheduleListMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockscheduleList) EXPECT() *MockscheduleListMockRecorder {
	return m.recorder
}

// Handle mocks base method.
func (m *MockscheduleList) Handle(ctx context.Context, userID int64, in dto.Input) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Handle", ctx, userID, in)
	ret0, _ := ret[0].(error)
	return ret0
}

// Handle indicates an expected call of Handle.
func (mr *MockscheduleListMockRecorder) Handle(ctx, userID, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Handle", reflect.TypeOf((*MockscheduleList)(nil).Handle), ctx, userID, in)
}

// MockscheduleInfo is a mock of scheduleInfo interface.
type MockscheduleInfo struct {
	ctrl     *gomock.Controller
	recorder *MockscheduleInfoMockRecorder
	isgomock struct{}
}

// MockscheduleInfoMockRecorder is the mock recorder for MockscheduleInfo.
type MockscheduleInfoMockRecorder struct {
	mock *MockscheduleInfo
}

// NewMockscheduleInfo creates a new mock instance.
func NewMockscheduleInfo(ctrl *gomock.Controller) *MockscheduleInfo {
	mock := &MockscheduleInfo{ctrl: ctrl}
	mock.recorder = &MockscheduleInfoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockscheduleInfo) EXPECT() *MockscheduleInfoMockRecorder {
	return m.recorder
}

// Handle mocks base method.
func (m *MockscheduleInfo) Handle(ctx context.Context, userID int64, in dto.Input) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Handle", ctx, userID, in)
	ret0, _ := ret[0].(error)
	return ret0
}

// Handle indicates an expected call of Handle.
func (mr *MockscheduleInfoMockRecorder) Handle(ctx, userID, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Handle", reflect.TypeOf((*MockscheduleInfo)(nil).Handle), ctx, userID, in)
}

// MockscheduleUpdate is a mock of scheduleUpdate interface.
type MockscheduleUpdate struct {
	ctrl     *gomock.Controller
	recorder *MockscheduleUpdateMockRecorder
	isgomock struct{}
}

// MockscheduleUpdateMockRecorder is the mock recorder for MockscheduleUpdate.
type MockscheduleUpdateMockRecorder struct {
	mock *MockscheduleUpdate
}

// NewMockscheduleUpdate creates a new mock instance.
func NewMockscheduleUpdate(ctrl *gomock.Controller) *MockscheduleUpdate {
	mock := &MockscheduleUpdate{ctrl: ctrl}
	mock.recorder = &MockscheduleUpdateMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockscheduleUpdate) EXPECT() *MockscheduleUpdateMockRecorder {
	return m.recorder
}

// Continue mocks base method.
func (m *MockscheduleUpdate) Continue(ctx context.Context, d *model.ScheduleEditDraft, in dto.Input) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Continue", ctx, d, in)
	ret0, _ := ret[0].(error)
	return ret0
}

// Continue indicates an expected call of Continue.
func (mr *MockscheduleUpdateMockRecorder) Continue(ctx, d, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Continue", reflect.TypeOf((*MockscheduleUpdate)(nil).Continue), ctx, d, in)
}

// Handle mocks base method.
func (m *MockscheduleUpdate) Handle(ctx context.Context, userID int64, in dto.Input) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Handle", ctx, userID, in)
	ret0, _ := ret[0].(error)
	return ret0
}

// Handle indicates an expected call of Handle.
func (mr *MockscheduleUpdateMockRecorder) Handle(ctx, userID, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Handle", reflect.TypeOf((*MockscheduleUpdate)(nil).Handle), ctx, userID, in)
}

// MockscheduleDelete is a mock of scheduleDelete interface.
type MockscheduleDelete struct {
	ctrl     *gomock.Controller
	recorder *MockscheduleDeleteMockRecorder
	isgomock struct{}
}

// MockscheduleDeleteMockRecorder is the mock recorder for MockscheduleDelete.
type MockscheduleDeleteMockRecorder struct {
	mock *MockscheduleDelete
}

// NewMockscheduleDelete creates a new mock instance.
func NewMockscheduleDelete(ctrl *gomock.Controller) *MockscheduleDelete {
	mock := &MockscheduleDelete{ctrl: ctrl}
	mock.recorder = &MockscheduleDeleteMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockscheduleDelete) EXPECT() *MockscheduleDeleteMockRecorder {
	return m.recorder
}

// Handle mocks base method.
func (m *MockscheduleDelete) Handle(ctx context.Context, userID int64, in dto.Input) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Handle", ctx, userID, in)
	ret0, _ := ret[0].(error)
	return ret0
}

// Handle indicates an expected call of Handle.
func (mr *MockscheduleDeleteMockRecorder) Handle(ctx, userID, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Handle", reflect.TypeOf((*MockscheduleDelete)(nil).Handle), ctx, userID, in)
}

// MocktrainingDraft is a mock of trainingDraft interface.
type MocktrainingDraft struct {
	ctrl     *gomock.Controller
	recorder *MocktrainingDraftMockRecorder
	isgomock struct{}
}

// MocktrainingDraftMockRecorder is the mock recorder for MocktrainingDraft.
type MocktrainingDraftMockRecorder struct {
	mock *MocktrainingDraft
}

// NewMocktrainingDraft creates a new mock instance.
func NewMocktrainingDraft(ctrl *gomock.Controller) *MocktrainingDraft {
	mock := &MocktrainingDraft{ctrl: ctrl}
	mock.recorder = &MocktrainingDraftMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocktrainingDraft) EXPECT() *MocktrainingDraftMockRecorder {
	return m.recorder
}

// GetDraftByUserID mocks base method.
func (m *MocktrainingDraft) GetDraftByUserID(ctx context.Context, userID int64) (*model.TrainingDraft, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDraftByUserID", ctx, userID)
	ret0, _ := ret[0].(*model.TrainingDraft)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDraftByUserID indicates an expected call of GetDraftByUserID.
func (mr *MocktrainingDraftMockRecorder) GetDraftByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDraftByUserID", reflect.TypeOf((*MocktrainingDraft)(nil).GetDraftByUserID), ctx, userID)
}

// MocktrainingEditDraft is a mock of trainingEditDraft interface.
type MocktrainingEditDraft struct {
	ctrl     *gomock.Controller
	recorder *MocktrainingEditDraftMockRecorder
	isgomock struct{}
}

// MocktrainingEditDraftMockRecorder is the mock recorder for MocktrainingEditDraft.
type MocktrainingEditDraftMockRecorder struct {
	mock *MocktrainingEditDraft
}

// NewMocktrainingEditDraft creates a new mock instance.
func NewMocktrainingEditDraft(ctrl *gomock.Controller) *MocktrainingEditDraft {
	mock := &MocktrainingEditDraft{ctrl: ctrl}
	mock.recorder = &MocktrainingEditDraftMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocktrainingEditDraft) EXPECT() *MocktrainingEditDraftMockRecorder {
	return m.recorder
}

// GetEditDraftByUserID mocks base method.
func (m *MocktrainingEditDraft) GetEditDraftByUserID(ctx context.Context, userID int64) (*model.TrainingEditDraft, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEditDraftByUserID", ctx, userID)
	ret0, _ := ret[0].(*model.TrainingEditDraft)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEditDraftByUserID indicates an expected call of GetEditDraftByUserID.
func (mr *MocktrainingEditDraftMockRecorder) GetEditDraftByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEditDraftByUserID", reflect.TypeOf((*MocktrainingEditDraft)(nil).GetEditDraftByUserID), ctx, userID)
}

// MockscheduleDraft is a mock of scheduleDraft interface.
type MockscheduleDraft struct {
	ctrl     *gomock.Controller
	recorder *MockscheduleDraftMockRecorder
	isgomock struct{}
}

// MockscheduleDraftMockRecorder is the mock recorder for MockscheduleDraft.
type MockscheduleDraftMockRecorder struct {
	mock *MockscheduleDraft
}

// NewMockscheduleDraft creates a new mock instance.
func NewMockscheduleDraft(ctrl *gomock.Controller) *MockscheduleDraft {
	mock := &MockscheduleDraft{ctrl: ctrl}
	mock.recorder = &MockscheduleDraftMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockscheduleDraft) EXPECT() *MockscheduleDraftMockRecorder {
	return m.recorder
}

// GetDraftByUserID mocks base method.
func (m *MockscheduleDraft) GetDraftByUserID(ctx context.Context, userID int64) (*model.ScheduleDraft, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDraftByUserID", ctx, userID)
	ret0, _ := ret[0].(*model.ScheduleDraft)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDraftByUserID indicates an expected call of GetDraftByUserID.
func (mr *MockscheduleDraftMockRecorder) GetDraftByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDraftByUserID", reflect.TypeOf((*MockscheduleDraft)(nil).GetDraftByUserID), ctx, userID)
}

// MockscheduleEditDraft is a mock of scheduleEditDraft interface.
type MockscheduleEditDraft struct {
	ctrl     *gomock.Controller
	recorder *MockscheduleEditDraftMockRecorder
	isgomock struct{}
}

// MockscheduleEditDraftMockRecorder is the mock recorder for MockscheduleEditDraft.
type MockscheduleEditDraftMockRecorder struct {
	mock *MockscheduleEditDraft
}

// NewMockscheduleEditDraft creates a new mock instance.
func NewMockscheduleEditDraft(ctrl *gomock.Controller) *MockscheduleEditDraft {
	mock := &MockscheduleEditDraft{ctrl: ctrl}
	mock.recorder = &MockscheduleEditDraftMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockscheduleEditDraft) EXPECT() *MockscheduleEditDraftMockRecorder {
	return m.recorder
}

// GetEditDraftByUserID mocks base method.
func (m *MockscheduleEditDraft) GetEditDraftByUserID(ctx context.Context, userID int64) (*model.ScheduleEditDraft, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEditDraftByUserID", ctx, userID)
	ret0, _ := ret[0].(*model.ScheduleEditDraft)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEditDraftByUserID indicates an expected call of GetEditDraftByUserID.
func (mr *MockscheduleEditDraftMockRecorder) GetEditDraftByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEditDraftByUserID", reflect.TypeOf((*MockscheduleEditDraft)(nil).GetEditDraftByUserID), ctx, userID)
}

// MockprofileEditDraft is a mock of profileEditDraft interface.
type MockprofileEditDraft struct {
	ctrl     *gomock.Controller
	recorder *MockprofileEditDraftMockRecorder
	isgomock struct{}
}

// MockprofileEditDraftMockRecorder is the mock recorder for MockprofileEditDraft.
type MockprofileEditDraftMockRecorder struct {
	mock *MockprofileEditDraft
}

// NewMockprofileEditDraft creates a new mock instance.
func NewMockprofileEditDraft(ctrl *gomock.Controller) *MockprofileEditDraft {
	mock := &MockprofileEditDraft{ctrl: ctrl}
	mock.recorder = &MockprofileEditDraftMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockprofileEditDraft) EXPECT() *MockprofileEditDraftMockRecorder {
	return m.recorder
}

// GetEditDraftByUserID mocks base method.
func (m *MockprofileEditDraft) GetEditDraftByUserID(ctx context.Context, userID int64) (*model.ProfileEditDraft, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEditDraftByUserID", ctx, userID)
	ret0, _ := ret[0].(*model.ProfileEditDraft)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEditDraftByUserID indicates an expected call of GetEditDraftByUserID.
func (mr *MockprofileEditDraftMockRecorder) GetEditDraftByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEditDraftByUserID", reflect.TypeOf((*MockprofileEditDraft)(nil).GetEditDraftByUserID), ctx, userID)
}

// MockcompetitionCreate is a mock of competitionCreate interface.
type MockcompetitionCreate struct {
	ctrl     *gomock.Controller
	recorder *MockcompetitionCreateMockRecorder
	isgomock struct{}
}

// MockcompetitionCreateMockRecorder is the mock recorder for MockcompetitionCreate.
type MockcompetitionCreateMockRecorder struct {
	mock *MockcompetitionCreate
}

// NewMockcompetitionCreate creates a new mock instance.
func NewMockcompetitionCreate(ctrl *gomock.Controller) *MockcompetitionCreate {
	mock := &MockcompetitionCreate{ctrl: ctrl}
	mock.recorder = &MockcompetitionCreateMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockcompetitionCreate) EXPECT() *MockcompetitionCreateMockRecorder {
	return m.recorder
}

// Begin mocks base method.
func (m *MockcompetitionCreate) Begin(ctx context.Context, u *model.User, in dto.Input) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Begin", ctx, u, in)
	ret0, _ := ret[0].(error)
	return ret0
}

// Begin indicates an expected call of Begin.
func (mr *MockcompetitionCreateMockRecorder) Begin(ctx, u, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Begin", reflect.TypeOf((*MockcompetitionCreate)(nil).Begin), ctx, u, in)
}

// Continue mocks base method.
func (m *MockcompetitionCreate) Continue(ctx context.Context, u *model.User, d *model.UserCompetitionDraft, in dto.Input) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Continue", ctx, u, d, in)
	ret0, _ := ret[0].(error)
	return ret0
}

// Continue indicates an expected call of Continue.
func (mr *MockcompetitionCreateMockRecorder) Continue(ctx, u, d, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Continue", reflect.TypeOf((*MockcompetitionCreate)(nil).Continue), ctx, u, d, in)
}

// MockcompetitionList is a mock of competitionList interface.
type MockcompetitionList struct {
	ctrl     *gomock.Controller
	recorder *MockcompetitionListMockRecorder
	isgomock struct{}
}

// MockcompetitionListMockRecorder is the mock recorder for MockcompetitionList.
type MockcompetitionListMockRecorder struct {
	mock *MockcompetitionList
}

// NewMockcompetitionList creates a new mock instance.
func NewMockcompetitionList(ctrl *gomock.Controller) *MockcompetitionList {
	mock := &MockcompetitionList{ctrl: ctrl}
	mock.recorder = &MockcompetitionListMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockcompetitionList) EXPECT() *MockcompetitionListMockRecorder {
	return m.recorder
}

// Handle mocks base method.
func (m *MockcompetitionList) Handle(ctx context.Context, u *model.User, in dto.Input) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Handle", ctx, u, in)
	ret0, _ := ret[0].(error)
	return ret0
}

// Handle indicates an expected call of Handle.
func (mr *MockcompetitionListMockRecorder) Handle(ctx, u, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Handle", reflect.TypeOf((*MockcompetitionList)(nil).Handle), ctx, u, in)
}

// MockcompetitionHistory is a mock of competitionHistory interface.
type MockcompetitionHistory struct {
	ctrl     *gomock.Controller
	recorder *MockcompetitionHistoryMockRecorder
	isgomock struct{}
}

// MockcompetitionHistoryMockRecorder is the mock recorder for MockcompetitionHistory.
type MockcompetitionHistoryMockRecorder struct {
	mock *MockcompetitionHistory
}

// NewMockcompetitionHistory creates a new mock instance.
func NewMockcompetitionHistory(ctrl *gomock.Controller) *MockcompetitionHistory {
	mock := &MockcompetitionHistory{ctrl: ctrl}
	mock.recorder = &MockcompetitionHistoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockcompetitionHistory) EXPECT() *MockcompetitionHistoryMockRecorder {
	return m.recorder
}

// Handle mocks base method.
func (m *MockcompetitionHistory) Handle(ctx context.Context, u *model.User, in dto.Input) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Handle", ctx, u, in)
	ret0, _ := ret[0].(error)
	return ret0
}

// Handle indicates an expected call of Handle.
func (mr *MockcompetitionHistoryMockRecorder) Handle(ctx, u, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Handle", reflect.TypeOf((*MockcompetitionHistory)(nil).Handle), ctx, u, in)
}

// MockcompetitionInfo is a mock of competitionInfo interface.
type MockcompetitionInfo struct {
	ctrl     *gomock.Controller
	recorder *MockcompetitionInfoMockRecorder
	isgomock struct{}
}

// MockcompetitionInfoMockRecorder is the mock recorder for MockcompetitionInfo.
type MockcompetitionInfoMockRecorder struct {
	mock *MockcompetitionInfo
}

// NewMockcompetitionInfo creates a new mock instance.
func NewMockcompetitionInfo(ctrl *gomock.Controller) *MockcompetitionInfo {
	mock := &MockcompetitionInfo{ctrl: ctrl}
	mock.recorder = &MockcompetitionInfoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockcompetitionInfo) EXPECT() *MockcompetitionInfoMockRecorder {
	return m.recorder
}

// Handle mocks base method.
func (m *MockcompetitionInfo) Handle(ctx context.Context, u *model.User, in dto.Input) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Handle", ctx, u, in)
	ret0, _ := ret[0].(error)
	return ret0
}

// Handle indicates an expected call of Handle.
func (mr *MockcompetitionInfoMockRecorder) Handle(ctx, u, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Handle", reflect.TypeOf((*MockcompetitionInfo)(nil).Handle), ctx, u, in)
}

// MockcompetitionUpdate is a mock of competitionUpdate interface.
type MockcompetitionUpdate struct {
	ctrl     *gomock.Controller
	recorder *MockcompetitionUpdateMockRecorder
	isgomock struct{}
}

// MockcompetitionUpdateMockRecorder is the mock recorder for MockcompetitionUpdate.
type MockcompetitionUpdateMockRecorder struct {
	mock *MockcompetitionUpdate
}

// NewMockcompetitionUpdate creates a new mock instance.
func NewMockcompetitionUpdate(ctrl *gomock.Controller) *MockcompetitionUpdate {
	mock := &MockcompetitionUpdate{ctrl: ctrl}
	mock.recorder = &MockcompetitionUpdateMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockcompetitionUpdate) EXPECT() *MockcompetitionUpdateMockRecorder {
	return m.recorder
}

// Continue mocks base method.
func (m *MockcompetitionUpdate) Continue(ctx context.Context, u *model.User, d *model.UserCompetitionEditDraft, in dto.Input) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Continue", ctx, u, d, in)
	ret0, _ := ret[0].(error)
	return ret0
}

// Continue indicates an expected call of Continue.
func (mr *MockcompetitionUpdateMockRecorder) Continue(ctx, u, d, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Continue", reflect.TypeOf((*MockcompetitionUpdate)(nil).Continue), ctx, u, d, in)
}

// Handle mocks base method.
func (m *MockcompetitionUpdate) Handle(ctx context.Context, u *model.User, in dto.Input) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Handle", ctx, u, in)
	ret0, _ := ret[0].(error)
	return ret0
}

// Handle indicates an expected call of Handle.
func (mr *MockcompetitionUpdateMockRecorder) Handle(ctx, u, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Handle", reflect.TypeOf((*MockcompetitionUpdate)(nil).Handle), ctx, u, in)
}

// MockcompetitionDelete is a mock of competitionDelete interface.
type MockcompetitionDelete struct {
	ctrl     *gomock.Controller
	recorder *MockcompetitionDeleteMockRecorder
	isgomock struct{}
}

// MockcompetitionDeleteMockRecorder is the mock recorder for MockcompetitionDelete.
type MockcompetitionDeleteMockRecorder struct {
	mock *MockcompetitionDelete
}

// NewMockcompetitionDelete creates a new mock instance.
func NewMockcompetitionDelete(ctrl *gomock.Controller) *MockcompetitionDelete {
	mock := &MockcompetitionDelete{ctrl: ctrl}
	mock.recorder = &MockcompetitionDeleteMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockcompetitionDelete) EXPECT() *MockcompetitionDeleteMockRecorder {
	return m.recorder
}

// Handle mocks base method.
func (m *MockcompetitionDelete) Handle(ctx context.Context, u *model.User, in dto.Input) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Handle", ctx, u, in)
	ret0, _ := ret[0].(error)
	return ret0
}

// Handle indicates an expected call of Handle.
func (mr *MockcompetitionDeleteMockRecorder) Handle(ctx, u, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Handle", reflect.TypeOf((*MockcompetitionDelete)(nil).Handle), ctx, u, in)
}

// MockcompetitionDraft is a mock of competitionDraft interface.
type MockcompetitionDraft struct {
	ctrl     *gomock.Controller
	recorder *MockcompetitionDraftMockRecorder
	isgomock struct{}
}

// MockcompetitionDraftMockRecorder is the mock recorder for MockcompetitionDraft.
type MockcompetitionDraftMockRecorder struct {
	mock *MockcompetitionDraft
}

// NewMockcompetitionDraft creates a new mock instance.
func NewMockcompetitionDraft(ctrl *gomock.Controller) *MockcompetitionDraft {
	mock := &MockcompetitionDraft{ctrl: ctrl}
	mock.recorder = &MockcompetitionDraftMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockcompetitionDraft) EXPECT() *MockcompetitionDraftMockRecorder {
	return m.recorder
}

// GetDraftByUserID mocks base method.
func (m *MockcompetitionDraft) GetDraftByUserID(ctx context.Context, userID int64) (*model.UserCompetitionDraft, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDraftByUserID", ctx, userID)
	ret0, _ := ret[0].(*model.UserCompetitionDraft)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDraftByUserID indicates an expected call of GetDraftByUserID.
func (mr *MockcompetitionDraftMockRecorder) GetDraftByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDraftByUserID", reflect.TypeOf((*MockcompetitionDraft)(nil).GetDraftByUserID), ctx, userID)
}

// MockcompetitionEditDraft is a mock of competitionEditDraft interface.
type MockcompetitionEditDraft struct {
	ctrl     *gomock.Controller
	recorder *MockcompetitionEditDraftMockRecorder
	isgomock struct{}
}

// MockcompetitionEditDraftMockRecorder is the mock recorder for MockcompetitionEditDraft.
type MockcompetitionEditDraftMockRecorder struct {
	mock *MockcompetitionEditDraft
}

// NewMockcompetitionEditDraft creates a new mock instance.
func NewMockcompetitionEditDraft(ctrl *gomock.Controller) *MockcompetitionEditDraft {
	mock := &MockcompetitionEditDraft{ctrl: ctrl}
	mock.recorder = &MockcompetitionEditDraftMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockcompetitionEditDraft) EXPECT() *MockcompetitionEditDraftMockRecorder {
	return m.recorder
}

// GetEditDraftByUserID mocks base method.
func (m *MockcompetitionEditDraft) GetEditDraftByUserID(ctx context.Context, userID int64) (*model.UserCompetitionEditDraft, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEditDraftByUserID", ctx, userID)
	ret0, _ := ret[0].(*model.UserCompetitionEditDraft)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEditDraftByUserID indicates an expected call of GetEditDraftByUserID.
func (mr *MockcompetitionEditDraftMockRecorder) GetEditDraftByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEditDraftByUserID", reflect.TypeOf((*MockcompetitionEditDraft)(nil).GetEditDraftByUserID), ctx, userID)
}

// MockcompetitionSubmit is a mock of competitionSubmit interface.
type MockcompetitionSubmit struct {
	ctrl     *gomock.Controller
	recorder *MockcompetitionSubmitMockRecorder
	isgomock struct{}
}

// MockcompetitionSubmitMockRecorder is the mock recorder for MockcompetitionSubmit.
type MockcompetitionSubmitMockRecorder struct {
	mock *MockcompetitionSubmit
}

// NewMockcompetitionSubmit creates a new mock instance.
func NewMockcompetitionSubmit(ctrl *gomock.Controller) *MockcompetitionSubmit {
	mock := &MockcompetitionSubmit{ctrl: ctrl}
	mock.recorder = &MockcompetitionSubmitMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockcompetitionSubmit) EXPECT() *MockcompetitionSubmitMockRecorder {
	return m.recorder
}

// Handle mocks base method.
func (m *MockcompetitionSubmit) Handle(ctx context.Context, u *model.User, in dto.Input) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Handle", ctx, u, in)
	ret0, _ := ret[0].(error)
	return ret0
}

// Handle indicates an expected call of Handle.
func (mr *MockcompetitionSubmitMockRecorder) Handle(ctx, u, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Handle", reflect.TypeOf((*MockcompetitionSubmit)(nil).Handle), ctx, u, in)
}

// MockcompetitionModerate is a mock of competitionModerate interface.
type MockcompetitionModerate struct {
	ctrl     *gomock.Controller
	recorder *MockcompetitionModerateMockRecorder
	isgomock struct{}
}

// MockcompetitionModerateMockRecorder is the mock recorder for MockcompetitionModerate.
type MockcompetitionModerateMockRecorder struct {
	mock *MockcompetitionModerate
}

// NewMockcompetitionModerate creates a new mock instance.
func NewMockcompetitionModerate(ctrl *gomock.Controller) *MockcompetitionModerate {
	mock := &MockcompetitionModerate{ctrl: ctrl}
	mock.recorder = &MockcompetitionModerateMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockcompetitionModerate) EXPECT() *MockcompetitionModerateMockRecorder {
	return m.recorder
}

// Continue mocks base method.
func (m *MockcompetitionModerate) Continue(ctx context.Context, u *model.User, d *model.CompetitionMergeDraft, in dto.Input) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Continue", ctx, u, d, in)
	ret0, _ := ret[0].(error)
	return ret0
}

// Continue indicates an expected call of Continue.
func (mr *MockcompetitionModerateMockRecorder) Continue(ctx, u, d, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Continue", reflect.TypeOf((*MockcompetitionModerate)(nil).Continue), ctx, u, d, in)
}

// Handle mocks base method.
func (m *MockcompetitionModerate) Handle(ctx context.Context, u *model.User, in dto.Input) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Handle", ctx, u, in)
	ret0, _ := ret[0].(error)
	return ret0
}

// Handle indicates an expected call of Handle.
func (mr *MockcompetitionModerateMockRecorder) Handle(ctx, u, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Handle", reflect.TypeOf((*MockcompetitionModerate)(nil).Handle), ctx, u, in)
}

// MockcompetitionMergeDraft is a mock of competitionMergeDraft interface.
type MockcompetitionMergeDraft struct {
	ctrl     *gomock.Controller
	recorder *MockcompetitionMergeDraftMockRecorder
	isgomock struct{}
}

// MockcompetitionMergeDraftMockRecorder is the mock recorder for MockcompetitionMergeDraft.
type MockcompetitionMergeDraftMockRecorder struct {
	mock *MockcompetitionMergeDraft
}

// NewMockcompetitionMergeDraft creates a new mock instance.
func NewMockcompetitionMergeDraft(ctrl *gomock.Controller) *MockcompetitionMergeDraft {
	mock := &MockcompetitionMergeDraft{ctrl: ctrl}
	mock.recorder = &MockcompetitionMergeDraftMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockcompetitionMergeDraft) EXPECT() *MockcompetitionMergeDraftMockRecorder {
	return m.recorder
}

// GetMergeDraftByUserID mocks base method.
func (m *MockcompetitionMergeDraft) GetMergeDraftByUserID(ctx context.Context, userID int64) (*model.CompetitionMergeDraft, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMergeDraftByUserID", ctx, userID)
	ret0, _ := ret[0].(*model.CompetitionMergeDraft)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMergeDraftByUserID indicates an expected call of GetMergeDraftByUserID.
func (mr *MockcompetitionMergeDraftMockRecorder) GetMergeDraftByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMergeDraftByUserID", reflect.TypeOf((*MockcompetitionMergeDraft)(nil).GetMergeDraftByUserID), ctx, userID)
}

// MockcatalogList is a mock of catalogList interface.
type MockcatalogList struct {
	ctrl     *gomock.Controller
	recorder *MockcatalogListMockRecorder
	isgomock struct{}
}

// MockcatalogListMockRecorder is the mock recorder for MockcatalogList.
type MockcatalogListMockRecorder struct {
	mock *MockcatalogList
}

// NewMockcatalogList creates a new mock instance.
func NewMockcatalogList(ctrl *gomock.Controller) *MockcatalogList {
	mock := &MockcatalogList{ctrl: ctrl}
	mock.recorder = &MockcatalogListMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockcatalogList) EXPECT() *MockcatalogListMockRecorder {
	return m.recorder
}

// Continue mocks base method.
func (m *MockcatalogList) Continue(ctx context.Context, u *model.User, d *model.CatalogCityDraft, in dto.Input) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Continue", ctx, u, d, in)
	ret0, _ := ret[0].(error)
	return ret0
}

// Continue indicates an expected call of Continue.
func (mr *MockcatalogListMockRecorder) Continue(ctx, u, d, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Continue", reflect.TypeOf((*MockcatalogList)(nil).Continue), ctx, u, d, in)
}

// Handle mocks base method.
func (m *MockcatalogList) Handle(ctx context.Context, u *model.User, in dto.Input) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Handle", ctx, u, in)
	ret0, _ := ret[0].(error)
	return ret0
}

// Handle indicates an expected call of Handle.
func (mr *MockcatalogListMockRecorder) Handle(ctx, u, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Handle", reflect.TypeOf((*MockcatalogList)(nil).Handle), ctx, u, in)
}

// MockcatalogInfo is a mock of catalogInfo interface.
type MockcatalogInfo struct {
	ctrl     *gomock.Controller
	recorder *MockcatalogInfoMockRecorder
	isgomock struct{}
}

// MockcatalogInfoMockRecorder is the mock recorder for MockcatalogInfo.
type MockcatalogInfoMockRecorder struct {
	mock *MockcatalogInfo
}

// NewMockcatalogInfo creates a new mock instance.
func NewMockcatalogInfo(ctrl *gomock.Controller) *MockcatalogInfo {
	mock := &MockcatalogInfo{ctrl: ctrl}
	mock.recorder = &MockcatalogInfoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockcatalogInfo) EXPECT() *MockcatalogInfoMockRecorder {
	return m.recorder
}

// Handle mocks base method.
func (m *MockcatalogInfo) Handle(ctx context.Context, u *model.User, in dto.Input) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Handle", ctx, u, in)
	ret0, _ := ret[0].(error)
	return ret0
}

// Handle indicates an expected call of Handle.
func (mr *MockcatalogInfoMockRecorder) Handle(ctx, u, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Handle", reflect.TypeOf((*MockcatalogInfo)(nil).Handle), ctx, u, in)
}

// MockcatalogAdd is a mock of catalogAdd interface.
type MockcatalogAdd struct {
	ctrl     *gomock.Controller
	recorder *MockcatalogAddMockRecorder
	isgomock struct{}
}

// MockcatalogAddMockRecorder is the mock recorder for MockcatalogAdd.
type MockcatalogAddMockRecorder struct {
	mock *MockcatalogAdd
}

// NewMockcatalogAdd creates a new mock instance.
func NewMockcatalogAdd(ctrl *gomock.Controller) *MockcatalogAdd {
	mock := &MockcatalogAdd{ctrl: ctrl}
	mock.recorder = &MockcatalogAddMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockcatalogAdd) EXPECT() *MockcatalogAddMockRecorder {
	return m.recorder
}

// Handle mocks base method.
func (m *MockcatalogAdd) Handle(ctx context.Context, u *model.User, in dto.Input) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Handle", ctx, u, in)
	ret0, _ := ret[0].(error)
	return ret0
}

// Handle indicates an expected call of Handle.
func (mr *MockcatalogAddMockRecorder) Handle(ctx, u, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Handle", reflect.TypeOf((*MockcatalogAdd)(nil).Handle), ctx, u, in)
}

// MockcatalogCityDraft is a mock of catalogCityDraft interface.
type MockcatalogCityDraft struct {
	ctrl     *gomock.Controller
	recorder *MockcatalogCityDraftMockRecorder
	isgomock struct{}
}

// MockcatalogCityDraftMockRecorder is the mock recorder for MockcatalogCityDraft.
type MockcatalogCityDraftMockRecorder struct {
	mock *MockcatalogCityDraft
}

// NewMockcatalogCityDraft creates a new mock instance.
func NewMockcatalogCityDraft(ctrl *gomock.Controller) *MockcatalogCityDraft {
	mock := &MockcatalogCityDraft{ctrl: ctrl}
	mock.recorder = &MockcatalogCityDraftMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockcatalogCityDraft) EXPECT() *MockcatalogCityDraftMockRecorder {
	return m.recorder
}

// GetCityDraftByUserID mocks base method.
func (m *MockcatalogCityDraft) GetCityDraftByUserID(ctx context.Context, userID int64) (*model.CatalogCityDraft, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCityDraftByUserID", ctx, userID)
	ret0, _ := ret[0].(*model.CatalogCityDraft)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCityDraftByUserID indicates an expected call of GetCityDraftByUserID.
func (mr *MockcatalogCityDraftMockRecorder) GetCityDraftByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCityDraftByUserID", reflect.TypeOf((*MockcatalogCityDraft)(nil).GetCityDraftByUserID), ctx, userID)
}
