// Code generated by MockGen. DO NOT EDIT.
// Source: contract.go
//
// Generated by this command:
//
//	mockgen -source=contract.go -destination=mock_schedule_test.go -package=schedule_test
//

// Package schedule_test is a generated GoMock package.
package schedule_test

import (
	context "context"
	reflect "reflect"

	model "github.com/khambek-archakov/jitLog/internal/model"
	dto "github.com/khambek-archakov/jitLog/internal/usecase/dto"
	gomock "go.uber.org/mock/gomock"
)

// Mockhandler is a mock of handler interface.
type Mockhandler struct {
	ctrl     *gomock.Controller
	recorder *MockhandlerMockRecorder
	isgomock struct{}
}

// MockhandlerMockRecorder is the mock recorder for Mockhandler.
type MockhandlerMockRecorder struct {
	mock *Mockhandler
}

// NewMockhandler creates a new mock instance.
func NewMockhandler(ctrl *gomock.Controller) *Mockhandler {
	mock := &Mockhandler{ctrl: ctrl}
	mock.recorder = &MockhandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mockhandler) EXPECT() *MockhandlerMockRecorder {
	return m.recorder
}

// Handle mocks base method.
func (m *Mockhandler) Handle(ctx context.Context, u *model.User, in dto.Input) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Handle", ctx, u, in)
	ret0, _ := ret[0].(error)
	return ret0
}

// Handle indicates an expected call of Handle.
func (mr *MockhandlerMockRecorder) Handle(ctx, u, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Handle", reflect.TypeOf((*Mockhandler)(nil).Handle), ctx, u, in)
}

// MockscheduleCreate is a mock of scheduleCreate interface.
type MockscheduleCreate struct {
	ctrl     *gomock.Controller
	recorder *MockscheduleCreateMockRecorder
	isgomock struct{}
}

// MockscheduleCreateMockRecorder is the mock recorder for MockscheduleCreate.
type MockscheduleCreateMockRecorder struct {
	mock *MockscheduleCreate
}

// NewMockscheduleCreate creates a new mock instance.
func NewMockscheduleCreate(ctrl *gomock.Controller) *MockscheduleCreate {
	mock := &MockscheduleCreate{ctrl: ctrl}
	mock.recorder = &MockscheduleCreateMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockscheduleCreate) EXPECT() *MockscheduleCreateMockRecorder {
	return m.recorder
}

// Begin mocks base method.
func (m *MockscheduleCreate) Begin(ctx context.Context, userID int64, in dto.Input) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Begin", ctx, userID, in)
	ret0, _ := ret[0].(error)
	return ret0
}

// Begin indicates an expected call of Begin.
func (mr *MockscheduleCreateMockRecorder) Begin(ctx, userID, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Begin", reflect.TypeOf((*MockscheduleCreate)(nil).Begin), ctx, userID, in)
}

// MockscheduleList is a mock of scheduleList interface.
type MockscheduleList struct {
	ctrl     *gomock.Controller
	recorder *MockscheduleListMockRecorder
	isgomock struct{}
}

// MockscheduleListMockRecorder is the mock recorder for MockscheduleList.
type MockscheduleListMockRecorder struct {
	mock *MockscheduleList
}

// NewMockscheduleList creates a new mock instance.
func NewMockscheduleList(ctrl *gomock.Controller) *MockscheduleList {
	mock := &MockscheduleList{ctrl: ctrl}
	mock.recorder = &MockscheduleListMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockscheduleList) EXPECT() *MockscheduleListMockRecorder {
	return m.recorder
}

// Handle mocks base method.
func (m *MockscheduleList) Handle(ctx context.Context, userID int64, in dto.Input) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Handle", ctx, userID, in)
	ret0, _ := ret[0].(error)
	return ret0
}

// Handle indicates an expected call of Handle.
func (mr *MockscheduleListMockRecorder) Handle(ctx, userID, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Handle", reflect.TypeOf((*MockscheduleList)(nil).Handle), ctx, userID, in)
}

// MockscheduleInfo is a mock of scheduleInfo interface.
type MockscheduleInfo struct {
	ctrl     *gomock.Controller
	recorder *MockscheduleInfoMockRecorder
	isgomock struct{}
}

// MockscheduleInfoMockRecorder is the mock recorder for MockscheduleInfo.
type MockscheduleInfoMockRecorder struct {
	mock *MockscheduleInfo
}

// NewMockscheduleInfo creates a new mock instance.
func NewMockscheduleInfo(ctrl *gomock.Controller) *MockscheduleInfo {
	mock := &MockscheduleInfo{ctrl: ctrl}
	mock.recorder = &MockscheduleInfoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockscheduleInfo) EXPECT() *MockscheduleInfoMockRecorder {
	return m.recorder
}

// Handle mocks base method.
func (m *MockscheduleInfo) Handle(ctx context.Context, userID int64, in dto.Input) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Handle", ctx, userID, in)
	ret0, _ := ret[0].(error)
	return ret0
}

// Handle indicates an expected call of Handle.
func (mr *MockscheduleInfoMockRecorder) Handle(ctx, userID, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Handle", reflect.TypeOf((*MockscheduleInfo)(nil).Handle), ctx, userID, in)
}

// MockscheduleUpdate is a mock of scheduleUpdate interface.
type MockscheduleUpdate struct {
	ctrl     *gomock.Controller
	recorder *MockscheduleUpdateMockRecorder
	isgomock struct{}
}

// MockscheduleUpdateMockRecorder is the mock recorder for MockscheduleUpdate.
type MockscheduleUpdateMockRecorder struct {
	mock *MockscheduleUpdate
}

// NewMockscheduleUpdate creates a new mock instance.
func NewMockscheduleUpdate(ctrl *gomock.Controller) *MockscheduleUpdate {
	mock := &MockscheduleUpdate{ctrl: ctrl}
	mock.recorder = &MockscheduleUpdateMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockscheduleUpdate) EXPECT() *MockscheduleUpdateMockRecorder {
	return m.recorder
}

// Handle mocks base method.
func (m *MockscheduleUpdate) Handle(ctx context.Context, userID int64, in dto.Input) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Handle", ctx, userID, in)
	ret0, _ := ret[0].(error)
	return ret0
}

// Handle indicates an expected call of Handle.
func (mr *MockscheduleUpdateMockRecorder) Handle(ctx, userID, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Handle", reflect.TypeOf((*MockscheduleUpdate)(nil).Handle), ctx, userID, in)
}

// MockscheduleDelete is a mock of scheduleDelete interface.
type MockscheduleDelete struct {
	ctrl     *gomock.Controller
	recorder *MockscheduleDeleteMockRecorder
	isgomock struct{}
}

// MockscheduleDeleteMockRecorder is the mock recorder for MockscheduleDelete.
type MockscheduleDeleteMockRecorder struct {
	mock *MockscheduleDelete
}

// NewMockscheduleDelete creates a new mock instance.
func NewMockscheduleDelete(ctrl *gomock.Controller) *MockscheduleDelete {
	mock := &MockscheduleDelete{ctrl: ctrl}
	mock.recorder = &MockscheduleDeleteMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockscheduleDelete) EXPECT() *MockscheduleDeleteMockRecorder {
	return m.recorder
}

// Handle mocks base method.
func (m *MockscheduleDelete) Handle(ctx context.Context, userID int64, in dto.Input) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Handle", ctx, userID, in)
	ret0, _ := ret[0].(error)
	return ret0
}

// Handle indicates an expected call of Handle.
func (mr *MockscheduleDeleteMockRecorder) Handle(ctx, userID, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Handle", reflect.TypeOf((*MockscheduleDelete)(nil).Handle), ctx, userID, in)
}
