// Code generated by MockGen. DO NOT EDIT.
// Source: contract.go
//
// Generated by this command:
//
//	mockgen -source=contract.go -destination=mock_training_test.go -package=training_test
//

// Package training_test is a generated GoMock package.
package training_test

import (
	context "context"
	reflect "reflect"

	model "github.com/khambek-archakov/jitLog/internal/model"
	dto "github.com/khambek-archakov/jitLog/internal/usecase/dto"
	gomock "go.uber.org/mock/gomock"
)

// Mockhandler is a mock of handler interface.
type Mockhandler struct {
	ctrl     *gomock.Controller
	recorder *MockhandlerMockRecorder
	isgomock struct{}
}

// MockhandlerMockRecorder is the mock recorder for Mockhandler.
type MockhandlerMockRecorder struct {
	mock *Mockhandler
}

// NewMockhandler creates a new mock instance.
func NewMockhandler(ctrl *gomock.Controller) *Mockhandler {
	mock := &Mockhandler{ctrl: ctrl}
	mock.recorder = &MockhandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mockhandler) EXPECT() *MockhandlerMockRecorder {
	return m.recorder
}

// Handle mocks base method.
func (m *Mockhandler) Handle(ctx context.Context, u *model.User, in dto.Input) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Handle", ctx, u, in)
	ret0, _ := ret[0].(error)
	return ret0
}

// Handle indicates an expected call of Handle.
func (mr *MockhandlerMockRecorder) Handle(ctx, u, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Handle", reflect.TypeOf((*Mockhandler)(nil).Handle), ctx, u, in)
}

// MocktrainingCreate is a mock of trainingCreate interface.
type MocktrainingCreate struct {
	ctrl     *gomock.Controller
	recorder *MocktrainingCreateMockRecorder
	isgomock struct{}
}

// MocktrainingCreateMockRecorder is the mock recorder for MocktrainingCreate.
type MocktrainingCreateMockRecorder struct {
	mock *MocktrainingCreate
}

// NewMocktrainingCreate creates a new mock instance.
func NewMocktrainingCreate(ctrl *gomock.Controller) *MocktrainingCreate {
	mock := &MocktrainingCreate{ctrl: ctrl}
	mock.recorder = &MocktrainingCreateMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocktrainingCreate) EXPECT() *MocktrainingCreateMockRecorder {
	return m.recorder
}

// Begin mocks base method.
func (m *MocktrainingCreate) Begin(ctx context.Context, userID int64, in dto.Input) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Begin", ctx, userID, in)
	ret0, _ := ret[0].(error)
	return ret0
}

// Begin indicates an expected call of Begin.
func (mr *MocktrainingCreateMockRecorder) Begin(ctx, userID, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Begin", reflect.TypeOf((*MocktrainingCreate)(nil).Begin), ctx, userID, in)
}

// MocktrainingInfo is a mock of trainingInfo interface.
type MocktrainingInfo struct {
	ctrl     *gomock.Controller
	recorder *MocktrainingInfoMockRecorder
	isgomock struct{}
}

// MocktrainingInfoMockRecorder is the mock recorder for MocktrainingInfo.
type MocktrainingInfoMockRecorder struct {
	mock *MocktrainingInfo
}

// NewMocktrainingInfo creates a new mock instance.
func NewMocktrainingInfo(ctrl *gomock.Controller) *MocktrainingInfo {
	mock := &MocktrainingInfo{ctrl: ctrl}
	mock.recorder = &MocktrainingInfoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocktrainingInfo) EXPECT() *MocktrainingInfoMockRecorder {
	return m.recorder
}

// Handle mocks base method.
func (m *MocktrainingInfo) Handle(ctx context.Context, userID int64, in dto.Input) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Handle", ctx, userID, in)
	ret0, _ := ret[0].(error)
	return ret0
}

// Handle indicates an expected call of Handle.
func (mr *MocktrainingInfoMockRecorder) Handle(ctx, userID, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Handle", reflect.TypeOf((*MocktrainingInfo)(nil).Handle), ctx, userID, in)
}

// MocktrainingHistory is a mock of trainingHistory interface.
type MocktrainingHistory struct {
	ctrl     *gomock.Controller
	recorder *MocktrainingHistoryMockRecorder
	isgomock struct{}
}

// MocktrainingHistoryMockRecorder is the mock recorder for MocktrainingHistory.
type MocktrainingHistoryMockRecorder struct {
	mock *MocktrainingHistory
}

// NewMocktrainingHistory creates a new mock instance.
func NewMocktrainingHistory(ctrl *gomock.Controller) *MocktrainingHistory {
	mock := &MocktrainingHistory{ctrl: ctrl}
	mock.recorder = &MocktrainingHistoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocktrainingHistory) EXPECT() *MocktrainingHistoryMockRecorder {
	return m.recorder
}

// Handle mocks base method.
func (m *MocktrainingHistory) Handle(ctx context.Context, userID int64, in dto.Input) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Handle", ctx, userID, in)
	ret0, _ := ret[0].(error)
	return ret0
}

// Handle indicates an expected call of Handle.
func (mr *MocktrainingHistoryMockRecorder) Handle(ctx, userID, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Handle", reflect.TypeOf((*MocktrainingHistory)(nil).Handle), ctx, userID, in)
}

// MocktrainingUpdate is a mock of trainingUpdate interface.
type MocktrainingUpdate struct {
	ctrl     *gomock.Controller
	recorder *MocktrainingUpdateMockRecorder
	isgomock struct{}
}

// MocktrainingUpdateMockRecorder is the mock recorder for MocktrainingUpdate.
type MocktrainingUpdateMockRecorder struct {
	mock *MocktrainingUpdate
}

// NewMocktrainingUpdate creates a new mock instance.
func NewMocktrainingUpdate(ctrl *gomock.Controller) *MocktrainingUpdate {
	mock := &MocktrainingUpdate{ctrl: ctrl}
	mock.recorder = &MocktrainingUpdateMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocktrainingUpdate) EXPECT() *MocktrainingUpdateMockRecorder {
	return m.recorder
}

// Handle mocks base method.
func (m *MocktrainingUpdate) Handle(ctx context.Context, userID int64, in dto.Input) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Handle", ctx, userID, in)
	ret0, _ := ret[0].(error)
	return ret0
}

// Handle indicates an expected call of Handle.
func (mr *MocktrainingUpdateMockRecorder) Handle(ctx, userID, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Handle", reflect.TypeOf((*MocktrainingUpdate)(nil).Handle), ctx, userID, in)
}

// MocktrainingDelete is a mock of trainingDelete interface.
type MocktrainingDelete struct {
	ctrl     *gomock.Controller
	recorder *MocktrainingDeleteMockRecorder
	isgomock struct{}
}

// MocktrainingDeleteMockRecorder is the mock recorder for MocktrainingDelete.
type MocktrainingDeleteMockRecorder struct {
	mock *MocktrainingDelete
}

// NewMocktrainingDelete creates a new mock instance.
func NewMocktrainingDelete(ctrl *gomock.Controller) *MocktrainingDelete {
	mock := &MocktrainingDelete{ctrl: ctrl}
	mock.recorder = &MocktrainingDeleteMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocktrainingDelete) EXPECT() *MocktrainingDeleteMockRecorder {
	return m.recorder
}

// Handle mocks base method.
func (m *MocktrainingDelete) Handle(ctx context.Context, userID int64, in dto.Input) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Handle", ctx, userID, in)
	ret0, _ := ret[0].(error)
	return ret0
}

// Handle indicates an expected call of Handle.
func (mr *MocktrainingDeleteMockRecorder) Handle(ctx, userID, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Handle", reflect.TypeOf((*MocktrainingDelete)(nil).Handle), ctx, userID, in)
}
