// Code generated by MockGen. DO NOT EDIT.
// Source: contract.go
//
// Generated by this command:
//
//	mockgen -source=contract.go -destination=mock_list_test.go -package=list_test
//

// Package list_test is a generated GoMock package.
package list_test

import (
	context "context"
	reflect "reflect"
	time "time"

	model "github.com/khambek-archakov/jitLog/internal/model"
	dto "github.com/khambek-archakov/jitLog/internal/usecase/dto"
	gomock "go.uber.org/mock/gomock"
)

// Mocksender is a mock of sender interface.
type Mocksender struct {
	ctrl     *gomock.Controller
	recorder *MocksenderMockRecorder
	isgomock struct{}
}

// MocksenderMockRecorder is the mock recorder for Mocksender.
type MocksenderMockRecorder struct {
	mock *Mocksender
}

// NewMocksender creates a new mock instance.
func NewMocksender(ctrl *gomock.Controller) *Mocksender {
	mock := &Mocksender{ctrl: ctrl}
	mock.recorder = &MocksenderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mocksender) EXPECT() *MocksenderMockRecorder {
	return m.recorder
}

// AnswerCallback mocks base method.
func (m *Mocksender) AnswerCallback(ctx context.Context, callbackID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AnswerCallback", ctx, callbackID)
	ret0, _ := ret[0].(error)
	return ret0
}

// AnswerCallback indicates an expected call of AnswerCallback.
func (mr *MocksenderMockRecorder) AnswerCallback(ctx, callbackID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AnswerCallback", reflect.TypeOf((*Mocksender)(nil).AnswerCallback), ctx, callbackID)
}

// AnswerCallbackWithText mocks base method.
func (m *Mocksender) AnswerCallbackWithText(ctx context.Context, callbackID, text string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AnswerCallbackWithText", ctx, callbackID, text)
	ret0, _ := ret[0].(error)
	return ret0
}

// AnswerCallbackWithText indicates an expected call of AnswerCallbackWithText.
func (mr *MocksenderMockRecorder) AnswerCallbackWithText(ctx, callbackID, text any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AnswerCallbackWithText", reflect.TypeOf((*Mocksender)(nil).AnswerCallbackWithText), ctx, callbackID, text)
}

// EditMessageWithKeyboard mocks base method.
func (m *Mocksender) EditMessageWithKeyboard(ctx context.Context, chatID int64, messageID int, text string, keyboard dto.Keyboard) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EditMessageWithKeyboard", ctx, chatID, messageID, text, keyboard)
	ret0, _ := ret[0].(error)
	return ret0
}

// EditMessageWithKeyboard indicates an expected call of EditMessageWithKeyboard.
func (mr *MocksenderMockRecorder) EditMessageWithKeyboard(ctx, chatID, messageID, text, keyboard any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EditMessageWithKeyboard", reflect.TypeOf((*Mocksender)(nil).EditMessageWithKeyboard), ctx, chatID, messageID, text, keyboard)
}

// Send mocks base method.
func (m *Mocksender) Send(ctx context.Context, chatID int64, text string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Send", ctx, chatID, text)
	ret0, _ := ret[0].(error)
	return ret0
}

// Send indicates an expected call of Send.
func (mr *MocksenderMockRecorder) Send(ctx, chatID, text any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Send", reflect.TypeOf((*Mocksender)(nil).Send), ctx, chatID, text)
}

// SendWithKeyboard mocks base method.
func (m *Mocksender) SendWithKeyboard(ctx context.Context, chatID int64, text string, keyboard dto.Keyboard) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendWithKeyboard", ctx, chatID, text, keyboard)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendWithKeyboard indicates an expected call of SendWithKeyboard.
func (mr *MocksenderMockRecorder) SendWithKeyboard(ctx, chatID, text, keyboard any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendWithKeyboard", reflect.TypeOf((*Mocksender)(nil).SendWithKeyboard), ctx, chatID, text, keyboard)
}

// MockcatalogRepo is a mock of catalogRepo interface.
type MockcatalogRepo struct {
	ctrl     *gomock.Controller
	recorder *MockcatalogRepoMockRecorder
	isgomock struct{}
}

// MockcatalogRepoMockRecorder is the mock recorder for MockcatalogRepo.
type MockcatalogRepoMockRecorder struct {
	mock *MockcatalogRepo
}

// NewMockcatalogRepo creates a new mock instance.
func NewMockcatalogRepo(ctrl *gomock.Controller) *MockcatalogRepo {
	mock := &MockcatalogRepo{ctrl: ctrl}
	mock.recorder = &MockcatalogRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockcatalogRepo) EXPECT() *MockcatalogRepoMockRecorder {
	return m.recorder
}

// DeleteCityDraft mocks base method.
func (m *MockcatalogRepo) DeleteCityDraft(ctx context.Context, userID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteCityDraft", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteCityDraft indicates an expected call of DeleteCityDraft.
func (mr *MockcatalogRepoMockRecorder) DeleteCityDraft(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteCityDraft", reflect.TypeOf((*MockcatalogRepo)(nil).DeleteCityDraft), ctx, userID)
}

// GetViewFilter mocks base method.
func (m *MockcatalogRepo) GetViewFilter(ctx context.Context, userID int64) (*model.CatalogViewFilter, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetViewFilter", ctx, userID)
	ret0, _ := ret[0].(*model.CatalogViewFilter)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetViewFilter indicates an expected call of GetViewFilter.
func (mr *MockcatalogRepoMockRecorder) GetViewFilter(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetViewFilter", reflect.TypeOf((*MockcatalogRepo)(nil).GetViewFilter), ctx, userID)
}

// ListCatalogUpcoming mocks base method.
func (m *MockcatalogRepo) ListCatalogUpcoming(ctx context.Context, today time.Time, city *string, limit, offset int) ([]*model.Competition, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListCatalogUpcoming", ctx, today, city, limit, offset)
	ret0, _ := ret[0].([]*model.Competition)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListCatalogUpcoming indicates an expected call of ListCatalogUpcoming.
func (mr *MockcatalogRepoMockRecorder) ListCatalogUpcoming(ctx, today, city, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListCatalogUpcoming", reflect.TypeOf((*MockcatalogRepo)(nil).ListCatalogUpcoming), ctx, today, city, limit, offset)
}

// SetCityDraft mocks base method.
func (m *MockcatalogRepo) SetCityDraft(ctx context.Context, userID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetCityDraft", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetCityDraft indicates an expected call of SetCityDraft.
func (mr *MockcatalogRepoMockRecorder) SetCityDraft(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetCityDraft", reflect.TypeOf((*MockcatalogRepo)(nil).SetCityDraft), ctx, userID)
}

// SetViewFilter mocks base method.
func (m *MockcatalogRepo) SetViewFilter(ctx context.Context, userID int64, city *string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetViewFilter", ctx, userID, city)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetViewFilter indicates an expected call of SetViewFilter.
func (mr *MockcatalogRepoMockRecorder) SetViewFilter(ctx, userID, city any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetViewFilter", reflect.TypeOf((*MockcatalogRepo)(nil).SetViewFilter), ctx, userID, city)
}
