// Code generated by MockGen. DO NOT EDIT.
// Source: contract.go
//
// Generated by this command:
//
//	mockgen -source=contract.go -destination=mock_competition_test.go -package=competition_test
//

// Package competition_test is a generated GoMock package.
package competition_test

import (
	context "context"
	reflect "reflect"

	model "github.com/khambek-archakov/jitLog/internal/model"
	dto "github.com/khambek-archakov/jitLog/internal/usecase/dto"
	gomock "go.uber.org/mock/gomock"
)

// Mockhandler is a mock of handler interface.
type Mockhandler struct {
	ctrl     *gomock.Controller
	recorder *MockhandlerMockRecorder
	isgomock struct{}
}

// MockhandlerMockRecorder is the mock recorder for Mockhandler.
type MockhandlerMockRecorder struct {
	mock *Mockhandler
}

// NewMockhandler creates a new mock instance.
func NewMockhandler(ctrl *gomock.Controller) *Mockhandler {
	mock := &Mockhandler{ctrl: ctrl}
	mock.recorder = &MockhandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mockhandler) EXPECT() *MockhandlerMockRecorder {
	return m.recorder
}

// Handle mocks base method.
func (m *Mockhandler) Handle(ctx context.Context, u *model.User, in dto.Input) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Handle", ctx, u, in)
	ret0, _ := ret[0].(error)
	return ret0
}

// Handle indicates an expected call of Handle.
func (mr *MockhandlerMockRecorder) Handle(ctx, u, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Handle", reflect.TypeOf((*Mockhandler)(nil).Handle), ctx, u, in)
}

// MockcompetitionCreate is a mock of competitionCreate interface.
type MockcompetitionCreate struct {
	ctrl     *gomock.Controller
	recorder *MockcompetitionCreateMockRecorder
	isgomock struct{}
}

// MockcompetitionCreateMockRecorder is the mock recorder for MockcompetitionCreate.
type MockcompetitionCreateMockRecorder struct {
	mock *MockcompetitionCreate
}

// NewMockcompetitionCreate creates a new mock instance.
func NewMockcompetitionCreate(ctrl *gomock.Controller) *MockcompetitionCreate {
	mock := &MockcompetitionCreate{ctrl: ctrl}
	mock.recorder = &MockcompetitionCreateMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockcompetitionCreate) EXPECT() *MockcompetitionCreateMockRecorder {
	return m.recorder
}

// Begin mocks base method.
func (m *MockcompetitionCreate) Begin(ctx context.Context, u *model.User, in dto.Input) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Begin", ctx, u, in)
	ret0, _ := ret[0].(error)
	return ret0
}

// Begin indicates an expected call of Begin.
func (mr *MockcompetitionCreateMockRecorder) Begin(ctx, u, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Begin", reflect.TypeOf((*MockcompetitionCreate)(nil).Begin), ctx, u, in)
}

// MockcompetitionList is a mock of competitionList interface.
type MockcompetitionList struct {
	ctrl     *gomock.Controller
	recorder *MockcompetitionListMockRecorder
	isgomock struct{}
}

// MockcompetitionListMockRecorder is the mock recorder for MockcompetitionList.
type MockcompetitionListMockRecorder struct {
	mock *MockcompetitionList
}

// NewMockcompetitionList creates a new mock instance.
func NewMockcompetitionList(ctrl *gomock.Controller) *MockcompetitionList {
	mock := &MockcompetitionList{ctrl: ctrl}
	mock.recorder = &MockcompetitionListMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockcompetitionList) EXPECT() *MockcompetitionListMockRecorder {
	return m.recorder
}

// Handle mocks base method.
func (m *MockcompetitionList) Handle(ctx context.Context, u *model.User, in dto.Input) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Handle", ctx, u, in)
	ret0, _ := ret[0].(error)
	return ret0
}

// Handle indicates an expected call of Handle.
func (mr *MockcompetitionListMockRecorder) Handle(ctx, u, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Handle", reflect.TypeOf((*MockcompetitionList)(nil).Handle), ctx, u, in)
}

// MockcompetitionHistory is a mock of competitionHistory interface.
type MockcompetitionHistory struct {
	ctrl     *gomock.Controller
	recorder *MockcompetitionHistoryMockRecorder
	isgomock struct{}
}

// MockcompetitionHistoryMockRecorder is the mock recorder for MockcompetitionHistory.
type MockcompetitionHistoryMockRecorder struct {
	mock *MockcompetitionHistory
}

// NewMockcompetitionHistory creates a new mock instance.
func NewMockcompetitionHistory(ctrl *gomock.Controller) *MockcompetitionHistory {
	mock := &MockcompetitionHistory{ctrl: ctrl}
	mock.recorder = &MockcompetitionHistoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockcompetitionHistory) EXPECT() *MockcompetitionHistoryMockRecorder {
	return m.recorder
}

// Handle mocks base method.
func (m *MockcompetitionHistory) Handle(ctx context.Context, u *model.User, in dto.Input) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Handle", ctx, u, in)
	ret0, _ := ret[0].(error)
	return ret0
}

// Handle indicates an expected call of Handle.
func (mr *MockcompetitionHistoryMockRecorder) Handle(ctx, u, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Handle", reflect.TypeOf((*MockcompetitionHistory)(nil).Handle), ctx, u, in)
}

// MockcompetitionInfo is a mock of competitionInfo interface.
type MockcompetitionInfo struct {
	ctrl     *gomock.Controller
	recorder *MockcompetitionInfoMockRecorder
	isgomock struct{}
}

// MockcompetitionInfoMockRecorder is the mock recorder for MockcompetitionInfo.
type MockcompetitionInfoMockRecorder struct {
	mock *MockcompetitionInfo
}

// NewMockcompetitionInfo creates a new mock instance.
func NewMockcompetitionInfo(ctrl *gomock.Controller) *MockcompetitionInfo {
	mock := &MockcompetitionInfo{ctrl: ctrl}
	mock.recorder = &MockcompetitionInfoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockcompetitionInfo) EXPECT() *MockcompetitionInfoMockRecorder {
	return m.recorder
}

// Handle mocks base method.
func (m *MockcompetitionInfo) Handle(ctx context.Context, u *model.User, in dto.Input) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Handle", ctx, u, in)
	ret0, _ := ret[0].(error)
	return ret0
}

// Handle indicates an expected call of Handle.
func (mr *MockcompetitionInfoMockRecorder) Handle(ctx, u, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Handle", reflect.TypeOf((*MockcompetitionInfo)(nil).Handle), ctx, u, in)
}

// MockcompetitionUpdate is a mock of competitionUpdate interface.
type MockcompetitionUpdate struct {
	ctrl     *gomock.Controller
	recorder *MockcompetitionUpdateMockRecorder
	isgomock struct{}
}

// MockcompetitionUpdateMockRecorder is the mock recorder for MockcompetitionUpdate.
type MockcompetitionUpdateMockRecorder struct {
	mock *MockcompetitionUpdate
}

// NewMockcompetitionUpdate creates a new mock instance.
func NewMockcompetitionUpdate(ctrl *gomock.Controller) *MockcompetitionUpdate {
	mock := &MockcompetitionUpdate{ctrl: ctrl}
	mock.recorder = &MockcompetitionUpdateMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockcompetitionUpdate) EXPECT() *MockcompetitionUpdateMockRecorder {
	return m.recorder
}

// Handle mocks base method.
func (m *MockcompetitionUpdate) Handle(ctx context.Context, u *model.User, in dto.Input) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Handle", ctx, u, in)
	ret0, _ := ret[0].(error)
	return ret0
}

// Handle indicates an expected call of Handle.
func (mr *MockcompetitionUpdateMockRecorder) Handle(ctx, u, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Handle", reflect.TypeOf((*MockcompetitionUpdate)(nil).Handle), ctx, u, in)
}

// MockcompetitionDelete is a mock of competitionDelete interface.
type MockcompetitionDelete struct {
	ctrl     *gomock.Controller
	recorder *MockcompetitionDeleteMockRecorder
	isgomock struct{}
}

// MockcompetitionDeleteMockRecorder is the mock recorder for MockcompetitionDelete.
type MockcompetitionDeleteMockRecorder struct {
	mock *MockcompetitionDelete
}

// NewMockcompetitionDelete creates a new mock instance.
func NewMockcompetitionDelete(ctrl *gomock.Controller) *MockcompetitionDelete {
	mock := &MockcompetitionDelete{ctrl: ctrl}
	mock.recorder = &MockcompetitionDeleteMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockcompetitionDelete) EXPECT() *MockcompetitionDeleteMockRecorder {
	return m.recorder
}

// Handle mocks base method.
func (m *MockcompetitionDelete) Handle(ctx context.Context, u *model.User, in dto.Input) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Handle", ctx, u, in)
	ret0, _ := ret[0].(error)
	return ret0
}

// Handle indicates an expected call of Handle.
func (mr *MockcompetitionDeleteMockRecorder) Handle(ctx, u, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Handle", reflect.TypeOf((*MockcompetitionDelete)(nil).Handle), ctx, u, in)
}

// MockcompetitionSubmit is a mock of competitionSubmit interface.
type MockcompetitionSubmit struct {
	ctrl     *gomock.Controller
	recorder *MockcompetitionSubmitMockRecorder
	isgomock struct{}
}

// MockcompetitionSubmitMockRecorder is the mock recorder for MockcompetitionSubmit.
type MockcompetitionSubmitMockRecorder struct {
	mock *MockcompetitionSubmit
}

// NewMockcompetitionSubmit creates a new mock instance.
func NewMockcompetitionSubmit(ctrl *gomock.Controller) *MockcompetitionSubmit {
	mock := &MockcompetitionSubmit{ctrl: ctrl}
	mock.recorder = &MockcompetitionSubmitMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockcompetitionSubmit) EXPECT() *MockcompetitionSubmitMockRecorder {
	return m.recorder
}

// Handle mocks base method.
func (m *MockcompetitionSubmit) Handle(ctx context.Context, u *model.User, in dto.Input) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Handle", ctx, u, in)
	ret0, _ := ret[0].(error)
	return ret0
}

// Handle indicates an expected call of Handle.
func (mr *MockcompetitionSubmitMockRecorder) Handle(ctx, u, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Handle", reflect.TypeOf((*MockcompetitionSubmit)(nil).Handle), ctx, u, in)
}

// MockcompetitionModerate is a mock of competitionModerate interface.
type MockcompetitionModerate struct {
	ctrl     *gomock.Controller
	recorder *MockcompetitionModerateMockRecorder
	isgomock struct{}
}

// MockcompetitionModerateMockRecorder is the mock recorder for MockcompetitionModerate.
type MockcompetitionModerateMockRecorder struct {
	mock *MockcompetitionModerate
}

// NewMockcompetitionModerate creates a new mock instance.
func NewMockcompetitionModerate(ctrl *gomock.Controller) *MockcompetitionModerate {
	mock := &MockcompetitionModerate{ctrl: ctrl}
	mock.recorder = &MockcompetitionModerateMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockcompetitionModerate) EXPECT() *MockcompetitionModerateMockRecorder {
	return m.recorder
}

// Handle mocks base method.
func (m *MockcompetitionModerate) Handle(ctx context.Context, u *model.User, in dto.Input) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Handle", ctx, u, in)
	ret0, _ := ret[0].(error)
	return ret0
}

// Handle indicates an expected call of Handle.
func (mr *MockcompetitionModerateMockRecorder) Handle(ctx, u, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Handle", reflect.TypeOf((*MockcompetitionModerate)(nil).Handle), ctx, u, in)
}
