// Code generated by MockGen. DO NOT EDIT.
// Source: contract.go
//
// Generated by this command:
//
//	mockgen -source=contract.go -destination=mock_moderate_test.go -package=moderate_test
//

// Package moderate_test is a generated GoMock package.
package moderate_test

import (
	context "context"
	reflect "reflect"

	model "github.com/khambek-archakov/jitLog/internal/model"
	dto "github.com/khambek-archakov/jitLog/internal/usecase/dto"
	gomock "go.uber.org/mock/gomock"
)

// Mocksender is a mock of sender interface.
type Mocksender struct {
	ctrl     *gomock.Controller
	recorder *MocksenderMockRecorder
	isgomock struct{}
}

// MocksenderMockRecorder is the mock recorder for Mocksender.
type MocksenderMockRecorder struct {
	mock *Mocksender
}

// NewMocksender creates a new mock instance.
func NewMocksender(ctrl *gomock.Controller) *Mocksender {
	mock := &Mocksender{ctrl: ctrl}
	mock.recorder = &MocksenderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mocksender) EXPECT() *MocksenderMockRecorder {
	return m.recorder
}

// AnswerCallback mocks base method.
func (m *Mocksender) AnswerCallback(ctx context.Context, callbackID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AnswerCallback", ctx, callbackID)
	ret0, _ := ret[0].(error)
	return ret0
}

// AnswerCallback indicates an expected call of AnswerCallback.
func (mr *MocksenderMockRecorder) AnswerCallback(ctx, callbackID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AnswerCallback", reflect.TypeOf((*Mocksender)(nil).AnswerCallback), ctx, callbackID)
}

// AnswerCallbackWithText mocks base method.
func (m *Mocksender) AnswerCallbackWithText(ctx context.Context, callbackID, text string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AnswerCallbackWithText", ctx, callbackID, text)
	ret0, _ := ret[0].(error)
	return ret0
}

// AnswerCallbackWithText indicates an expected call of AnswerCallbackWithText.
func (mr *MocksenderMockRecorder) AnswerCallbackWithText(ctx, callbackID, text any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AnswerCallbackWithText", reflect.TypeOf((*Mocksender)(nil).AnswerCallbackWithText), ctx, callbackID, text)
}

// EditMessageWithKeyboard mocks base method.
func (m *Mocksender) EditMessageWithKeyboard(ctx context.Context, chatID int64, messageID int, text string, keyboard dto.Keyboard) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EditMessageWithKeyboard", ctx, chatID, messageID, text, keyboard)
	ret0, _ := ret[0].(error)
	return ret0
}

// EditMessageWithKeyboard indicates an expected call of EditMessageWithKeyboard.
func (mr *MocksenderMockRecorder) EditMessageWithKeyboard(ctx, chatID, messageID, text, keyboard any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EditMessageWithKeyboard", reflect.TypeOf((*Mocksender)(nil).EditMessageWithKeyboard), ctx, chatID, messageID, text, keyboard)
}

// Send mocks base method.
func (m *Mocksender) Send(ctx context.Context, chatID int64, text string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Send", ctx, chatID, text)
	ret0, _ := ret[0].(error)
	return ret0
}

// Send indicates an expected call of Send.
func (mr *MocksenderMockRecorder) Send(ctx, chatID, text any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Send", reflect.TypeOf((*Mocksender)(nil).Send), ctx, chatID, text)
}

// SendWithKeyboard mocks base method.
func (m *Mocksender) SendWithKeyboard(ctx context.Context, chatID int64, text string, keyboard dto.Keyboard) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendWithKeyboard", ctx, chatID, text, keyboard)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendWithKeyboard indicates an expected call of SendWithKeyboard.
func (mr *MocksenderMockRecorder) SendWithKeyboard(ctx, chatID, text, keyboard any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendWithKeyboard", reflect.TypeOf((*Mocksender)(nil).SendWithKeyboard), ctx, chatID, text, keyboard)
}

// Mockrepo is a mock of repo interface.
type Mockrepo struct {
	ctrl     *gomock.Controller
	recorder *MockrepoMockRecorder
	isgomock struct{}
}

// MockrepoMockRecorder is the mock recorder for Mockrepo.
type MockrepoMockRecorder struct {
	mock *Mockrepo
}

// NewMockrepo creates a new mock instance.
func NewMockrepo(ctrl *gomock.Controller) *Mockrepo {
	mock := &Mockrepo{ctrl: ctrl}
	mock.recorder = &MockrepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mockrepo) EXPECT() *MockrepoMockRecorder {
	return m.recorder
}

// DeleteMergeDraft mocks base method.
func (m *Mockrepo) DeleteMergeDraft(ctx context.Context, userID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteMergeDraft", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteMergeDraft indicates an expected call of DeleteMergeDraft.
func (mr *MockrepoMockRecorder) DeleteMergeDraft(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteMergeDraft", reflect.TypeOf((*Mockrepo)(nil).DeleteMergeDraft), ctx, userID)
}

// ListOwnersByCompetitionID mocks base method.
func (m *Mockrepo) ListOwnersByCompetitionID(ctx context.Context, competitionID int64) ([]int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListOwnersByCompetitionID", ctx, competitionID)
	ret0, _ := ret[0].([]int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListOwnersByCompetitionID indicates an expected call of ListOwnersByCompetitionID.
func (mr *MockrepoMockRecorder) ListOwnersByCompetitionID(ctx, competitionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListOwnersByCompetitionID", reflect.TypeOf((*Mockrepo)(nil).ListOwnersByCompetitionID), ctx, competitionID)
}

// MergeCompetition mocks base method.
func (m *Mockrepo) MergeCompetition(ctx context.Context, pendingID, existingID int64) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MergeCompetition", ctx, pendingID, existingID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MergeCompetition indicates an expected call of MergeCompetition.
func (mr *MockrepoMockRecorder) MergeCompetition(ctx, pendingID, existingID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MergeCompetition", reflect.TypeOf((*Mockrepo)(nil).MergeCompetition), ctx, pendingID, existingID)
}

// SearchCompetitionsByTitle mocks base method.
func (m *Mockrepo) SearchCompetitionsByTitle(ctx context.Context, term string, excludeID int64, limit int) ([]*model.Competition, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchCompetitionsByTitle", ctx, term, excludeID, limit)
	ret0, _ := ret[0].([]*model.Competition)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchCompetitionsByTitle indicates an expected call of SearchCompetitionsByTitle.
func (mr *MockrepoMockRecorder) SearchCompetitionsByTitle(ctx, term, excludeID, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchCompetitionsByTitle", reflect.TypeOf((*Mockrepo)(nil).SearchCompetitionsByTitle), ctx, term, excludeID, limit)
}

// SetCompetitionStatus mocks base method.
func (m *Mockrepo) SetCompetitionStatus(ctx context.Context, id int64, status model.CompetitionStatus) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetCompetitionStatus", ctx, id, status)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetCompetitionStatus indicates an expected call of SetCompetitionStatus.
func (mr *MockrepoMockRecorder) SetCompetitionStatus(ctx, id, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetCompetitionStatus", reflect.TypeOf((*Mockrepo)(nil).SetCompetitionStatus), ctx, id, status)
}

// SetMergeDraft mocks base method.
func (m *Mockrepo) SetMergeDraft(ctx context.Context, userID, pendingCompetitionID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetMergeDraft", ctx, userID, pendingCompetitionID)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetMergeDraft indicates an expected call of SetMergeDraft.
func (mr *MockrepoMockRecorder) SetMergeDraft(ctx, userID, pendingCompetitionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetMergeDraft", reflect.TypeOf((*Mockrepo)(nil).SetMergeDraft), ctx, userID, pendingCompetitionID)
}

// MockuserRepo is a mock of userRepo interface.
type MockuserRepo struct {
	ctrl     *gomock.Controller
	recorder *MockuserRepoMockRecorder
	isgomock struct{}
}

// MockuserRepoMockRecorder is the mock recorder for MockuserRepo.
type MockuserRepoMockRecorder struct {
	mock *MockuserRepo
}

// NewMockuserRepo creates a new mock instance.
func NewMockuserRepo(ctrl *gomock.Controller) *MockuserRepo {
	mock := &MockuserRepo{ctrl: ctrl}
	mock.recorder = &MockuserRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockuserRepo) EXPECT() *MockuserRepoMockRecorder {
	return m.recorder
}

// GetByID mocks base method.
func (m *MockuserRepo) GetByID(ctx context.Context, id int64) (*model.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*model.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockuserRepoMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockuserRepo)(nil).GetByID), ctx, id)
}
