// Code generated by MockGen. DO NOT EDIT.
// Source: contract.go
//
// Generated by this command:
//
//	mockgen -source=contract.go -destination=mock_update_test.go -package=update_test
//

// Package update_test is a generated GoMock package.
package update_test

import (
	context "context"
	reflect "reflect"
	time "time"

	model "github.com/khambek-archakov/jitLog/internal/model"
	dto "github.com/khambek-archakov/jitLog/internal/usecase/dto"
	gomock "go.uber.org/mock/gomock"
)

// Mocksender is a mock of sender interface.
type Mocksender struct {
	ctrl     *gomock.Controller
	recorder *MocksenderMockRecorder
	isgomock struct{}
}

// MocksenderMockRecorder is the mock recorder for Mocksender.
type MocksenderMockRecorder struct {
	mock *Mocksender
}

// NewMocksender creates a new mock instance.
func NewMocksender(ctrl *gomock.Controller) *Mocksender {
	mock := &Mocksender{ctrl: ctrl}
	mock.recorder = &MocksenderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mocksender) EXPECT() *MocksenderMockRecorder {
	return m.recorder
}

// AnswerCallback mocks base method.
func (m *Mocksender) AnswerCallback(ctx context.Context, callbackID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AnswerCallback", ctx, callbackID)
	ret0, _ := ret[0].(error)
	return ret0
}

// AnswerCallback indicates an expected call of AnswerCallback.
func (mr *MocksenderMockRecorder) AnswerCallback(ctx, callbackID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AnswerCallback", reflect.TypeOf((*Mocksender)(nil).AnswerCallback), ctx, callbackID)
}

// AnswerCallbackWithText mocks base method.
func (m *Mocksender) AnswerCallbackWithText(ctx context.Context, callbackID, text string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AnswerCallbackWithText", ctx, callbackID, text)
	ret0, _ := ret[0].(error)
	return ret0
}

// AnswerCallbackWithText indicates an expected call of AnswerCallbackWithText.
func (mr *MocksenderMockRecorder) AnswerCallbackWithText(ctx, callbackID, text any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AnswerCallbackWithText", reflect.TypeOf((*Mocksender)(nil).AnswerCallbackWithText), ctx, callbackID, text)
}

// EditMessageWithKeyboard mocks base method.
func (m *Mocksender) EditMessageWithKeyboard(ctx context.Context, chatID int64, messageID int, text string, keyboard dto.Keyboard) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EditMessageWithKeyboard", ctx, chatID, messageID, text, keyboard)
	ret0, _ := ret[0].(error)
	return ret0
}

// EditMessageWithKeyboard indicates an expected call of EditMessageWithKeyboard.
func (mr *MocksenderMockRecorder) EditMessageWithKeyboard(ctx, chatID, messageID, text, keyboard any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EditMessageWithKeyboard", reflect.TypeOf((*Mocksender)(nil).EditMessageWithKeyboard), ctx, chatID, messageID, text, keyboard)
}

// Send mocks base method.
func (m *Mocksender) Send(ctx context.Context, chatID int64, text string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Send", ctx, chatID, text)
	ret0, _ := ret[0].(error)
	return ret0
}

// Send indicates an expected call of Send.
func (mr *MocksenderMockRecorder) Send(ctx, chatID, text any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Send", reflect.TypeOf((*Mocksender)(nil).Send), ctx, chatID, text)
}

// SendWithKeyboard mocks base method.
func (m *Mocksender) SendWithKeyboard(ctx context.Context, chatID int64, text string, keyboard dto.Keyboard) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendWithKeyboard", ctx, chatID, text, keyboard)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendWithKeyboard indicates an expected call of SendWithKeyboard.
func (mr *MocksenderMockRecorder) SendWithKeyboard(ctx, chatID, text, keyboard any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendWithKeyboard", reflect.TypeOf((*Mocksender)(nil).SendWithKeyboard), ctx, chatID, text, keyboard)
}

// MocktrainingRepo is a mock of trainingRepo interface.
type MocktrainingRepo struct {
	ctrl     *gomock.Controller
	recorder *MocktrainingRepoMockRecorder
	isgomock struct{}
}

// MocktrainingRepoMockRecorder is the mock recorder for MocktrainingRepo.
type MocktrainingRepoMockRecorder struct {
	mock *MocktrainingRepo
}

// NewMocktrainingRepo creates a new mock instance.
func NewMocktrainingRepo(ctrl *gomock.Controller) *MocktrainingRepo {
	mock := &MocktrainingRepo{ctrl: ctrl}
	mock.recorder = &MocktrainingRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocktrainingRepo) EXPECT() *MocktrainingRepoMockRecorder {
	return m.recorder
}

// DeleteEditDraft mocks base method.
func (m *MocktrainingRepo) DeleteEditDraft(ctx context.Context, userID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteEditDraft", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteEditDraft indicates an expected call of DeleteEditDraft.
func (mr *MocktrainingRepoMockRecorder) DeleteEditDraft(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteEditDraft", reflect.TypeOf((*MocktrainingRepo)(nil).DeleteEditDraft), ctx, userID)
}

// GetTraining mocks base method.
func (m *MocktrainingRepo) GetTraining(ctx context.Context, id int64) (*model.Training, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTraining", ctx, id)
	ret0, _ := ret[0].(*model.Training)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTraining indicates an expected call of GetTraining.
func (mr *MocktrainingRepoMockRecorder) GetTraining(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTraining", reflect.TypeOf((*MocktrainingRepo)(nil).GetTraining), ctx, id)
}

// SetEditDraft mocks base method.
func (m *MocktrainingRepo) SetEditDraft(ctx context.Context, userID, trainingID int64, field model.TrainingEditField) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetEditDraft", ctx, userID, trainingID, field)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetEditDraft indicates an expected call of SetEditDraft.
func (mr *MocktrainingRepoMockRecorder) SetEditDraft(ctx, userID, trainingID, field any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetEditDraft", reflect.TypeOf((*MocktrainingRepo)(nil).SetEditDraft), ctx, userID, trainingID, field)
}

// UpdateTraining mocks base method.
func (m *MocktrainingRepo) UpdateTraining(ctx context.Context, id int64, date time.Time, trainingType model.TrainingType, durationMinutes int32, notes *string) (*model.Training, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTraining", ctx, id, date, trainingType, durationMinutes, notes)
	ret0, _ := ret[0].(*model.Training)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateTraining indicates an expected call of UpdateTraining.
func (mr *MocktrainingRepoMockRecorder) UpdateTraining(ctx, id, date, trainingType, durationMinutes, notes any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTraining", reflect.TypeOf((*MocktrainingRepo)(nil).UpdateTraining), ctx, id, date, trainingType, durationMinutes, notes)
}
