// Code generated by MockGen. DO NOT EDIT.
// Source: contract.go
//
// Generated by this command:
//
//	mockgen -source=contract.go -destination=mock_stats_test.go -package=stats_test
//

// Package stats_test is a generated GoMock package.
package stats_test

import (
	context "context"
	reflect "reflect"

	model "github.com/khambek-archakov/jitLog/internal/model"
	dto "github.com/khambek-archakov/jitLog/internal/usecase/dto"
	gomock "go.uber.org/mock/gomock"
)

// Mocksender is a mock of sender interface.
type Mocksender struct {
	ctrl     *gomock.Controller
	recorder *MocksenderMockRecorder
	isgomock struct{}
}

// MocksenderMockRecorder is the mock recorder for Mocksender.
type MocksenderMockRecorder struct {
	mock *Mocksender
}

// NewMocksender creates a new mock instance.
func NewMocksender(ctrl *gomock.Controller) *Mocksender {
	mock := &Mocksender{ctrl: ctrl}
	mock.recorder = &MocksenderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mocksender) EXPECT() *MocksenderMockRecorder {
	return m.recorder
}

// AnswerCallback mocks base method.
func (m *Mocksender) AnswerCallback(ctx context.Context, callbackID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AnswerCallback", ctx, callbackID)
	ret0, _ := ret[0].(error)
	return ret0
}

// AnswerCallback indicates an expected call of AnswerCallback.
func (mr *MocksenderMockRecorder) AnswerCallback(ctx, callbackID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AnswerCallback", reflect.TypeOf((*Mocksender)(nil).AnswerCallback), ctx, callbackID)
}

// AnswerCallbackWithText mocks base method.
func (m *Mocksender) AnswerCallbackWithText(ctx context.Context, callbackID, text string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AnswerCallbackWithText", ctx, callbackID, text)
	ret0, _ := ret[0].(error)
	return ret0
}

// AnswerCallbackWithText indicates an expected call of AnswerCallbackWithText.
func (mr *MocksenderMockRecorder) AnswerCallbackWithText(ctx, callbackID, text any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AnswerCallbackWithText", reflect.TypeOf((*Mocksender)(nil).AnswerCallbackWithText), ctx, callbackID, text)
}

// EditMessageWithKeyboard mocks base method.
func (m *Mocksender) EditMessageWithKeyboard(ctx context.Context, chatID int64, messageID int, text string, keyboard dto.Keyboard) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EditMessageWithKeyboard", ctx, chatID, messageID, text, keyboard)
	ret0, _ := ret[0].(error)
	return ret0
}

// EditMessageWithKeyboard indicates an expected call of EditMessageWithKeyboard.
func (mr *MocksenderMockRecorder) EditMessageWithKeyboard(ctx, chatID, messageID, text, keyboard any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EditMessageWithKeyboard", reflect.TypeOf((*Mocksender)(nil).EditMessageWithKeyboard), ctx, chatID, messageID, text, keyboard)
}

// Send mocks base method.
func (m *Mocksender) Send(ctx context.Context, chatID int64, text string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Send", ctx, chatID, text)
	ret0, _ := ret[0].(error)
	return ret0
}

// Send indicates an expected call of Send.
func (mr *MocksenderMockRecorder) Send(ctx, chatID, text any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Send", reflect.TypeOf((*Mocksender)(nil).Send), ctx, chatID, text)
}

// SendWithKeyboard mocks base method.
func (m *Mocksender) SendWithKeyboard(ctx context.Context, chatID int64, text string, keyboard dto.Keyboard) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendWithKeyboard", ctx, chatID, text, keyboard)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendWithKeyboard indicates an expected call of SendWithKeyboard.
func (mr *MocksenderMockRecorder) SendWithKeyboard(ctx, chatID, text, keyboard any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendWithKeyboard", reflect.TypeOf((*Mocksender)(nil).SendWithKeyboard), ctx, chatID, text, keyboard)
}

// MocktrainingRepo is a mock of trainingRepo interface.
type MocktrainingRepo struct {
	ctrl     *gomock.Controller
	recorder *MocktrainingRepoMockRecorder
	isgomock struct{}
}

// MocktrainingRepoMockRecorder is the mock recorder for MocktrainingRepo.
type MocktrainingRepoMockRecorder struct {
	mock *MocktrainingRepo
}

// NewMocktrainingRepo creates a new mock instance.
func NewMocktrainingRepo(ctrl *gomock.Controller) *MocktrainingRepo {
	mock := &MocktrainingRepo{ctrl: ctrl}
	mock.recorder = &MocktrainingRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocktrainingRepo) EXPECT() *MocktrainingRepoMockRecorder {
	return m.recorder
}

// ListAllTrainings mocks base method.
func (m *MocktrainingRepo) ListAllTrainings(ctx context.Context, userID int64) ([]*model.Training, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAllTrainings", ctx, userID)
	ret0, _ := ret[0].([]*model.Training)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAllTrainings indicates an expected call of ListAllTrainings.
func (mr *MocktrainingRepoMockRecorder) ListAllTrainings(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAllTrainings", reflect.TypeOf((*MocktrainingRepo)(nil).ListAllTrainings), ctx, userID)
}

// MockbeltRepo is a mock of beltRepo interface.
type MockbeltRepo struct {
	ctrl     *gomock.Controller
	recorder *MockbeltRepoMockRecorder
	isgomock struct{}
}

// MockbeltRepoMockRecorder is the mock recorder for MockbeltRepo.
type MockbeltRepoMockRecorder struct {
	mock *MockbeltRepo
}

// NewMockbeltRepo creates a new mock instance.
func NewMockbeltRepo(ctrl *gomock.Controller) *MockbeltRepo {
	mock := &MockbeltRepo{ctrl: ctrl}
	mock.recorder = &MockbeltRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockbeltRepo) EXPECT() *MockbeltRepoMockRecorder {
	return m.recorder
}

// ListBeltPromotions mocks base method.
func (m *MockbeltRepo) ListBeltPromotions(ctx context.Context, userID int64) ([]*model.BeltPromotion, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListBeltPromotions", ctx, userID)
	ret0, _ := ret[0].([]*model.BeltPromotion)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListBeltPromotions indicates an expected call of ListBeltPromotions.
func (mr *MockbeltRepoMockRecorder) ListBeltPromotions(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListBeltPromotions", reflect.TypeOf((*MockbeltRepo)(nil).ListBeltPromotions), ctx, userID)
}
