// Code generated by MockGen. DO NOT EDIT.
// Source: contract.go
//
// Generated by this command:
//
//	mockgen -source=contract.go -destination=mock_tgbotapi_test.go -package=tgbotapi_test
//

// Package tgbotapi_test is a generated GoMock package.
package tgbotapi_test

import (
	reflect "reflect"

	tgbotapi "github.com/go-telegram-bot-api/telegram-bot-api/v5"
	gomock "go.uber.org/mock/gomock"
)

// Mocktransport is a mock of transport interface.
type Mocktransport struct {
	ctrl     *gomock.Controller
	recorder *MocktransportMockRecorder
	isgomock struct{}
}

// MocktransportMockRecorder is the mock recorder for Mocktransport.
type MocktransportMockRecorder struct {
	mock *Mocktransport
}

// NewMocktransport creates a new mock instance.
func NewMocktransport(ctrl *gomock.Controller) *Mocktransport {
	mock := &Mocktransport{ctrl: ctrl}
	mock.recorder = &MocktransportMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mocktransport) EXPECT() *MocktransportMockRecorder {
	return m.recorder
}

// Request mocks base method.
func (m *Mocktransport) Request(c tgbotapi.Chattable) (*tgbotapi.APIResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Request", c)
	ret0, _ := ret[0].(*tgbotapi.APIResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Request indicates an expected call of Request.
func (mr *MocktransportMockRecorder) Request(c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Request", reflect.TypeOf((*Mocktransport)(nil).Request), c)
}

// Send mocks base method.
func (m *Mocktransport) Send(c tgbotapi.Chattable) (tgbotapi.Message, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Send", c)
	ret0, _ := ret[0].(tgbotapi.Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Send indicates an expected call of Send.
func (mr *MocktransportMockRecorder) Send(c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Send", reflect.TypeOf((*Mocktransport)(nil).Send), c)
}
