// Code generated by MockGen. DO NOT EDIT.
// Source: contract.go
//
// Generated by this command:
//
//	mockgen -source=contract.go -destination=mock_catalog_test.go -package=catalog_test
//

// Package catalog_test is a generated GoMock package.
package catalog_test

import (
	context "context"
	reflect "reflect"

	model "github.com/khambek-archakov/jitLog/internal/model"
	dto "github.com/khambek-archakov/jitLog/internal/usecase/dto"
	gomock "go.uber.org/mock/gomock"
)

// Mockhandler is a mock of handler interface.
type Mockhandler struct {
	ctrl     *gomock.Controller
	recorder *MockhandlerMockRecorder
	isgomock struct{}
}

// MockhandlerMockRecorder is the mock recorder for Mockhandler.
type MockhandlerMockRecorder struct {
	mock *Mockhandler
}

// NewMockhandler creates a new mock instance.
func NewMockhandler(ctrl *gomock.Controller) *Mockhandler {
	mock := &Mockhandler{ctrl: ctrl}
	mock.recorder = &MockhandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mockhandler) EXPECT() *MockhandlerMockRecorder {
	return m.recorder
}

// Handle mocks base method.
func (m *Mockhandler) Handle(ctx context.Context, u *model.User, in dto.Input) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Handle", ctx, u, in)
	ret0, _ := ret[0].(error)
	return ret0
}

// Handle indicates an expected call of Handle.
func (mr *MockhandlerMockRecorder) Handle(ctx, u, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Handle", reflect.TypeOf((*Mockhandler)(nil).Handle), ctx, u, in)
}

// MockcatalogList is a mock of catalogList interface.
type MockcatalogList struct {
	ctrl     *gomock.Controller
	recorder *MockcatalogListMockRecorder
	isgomock struct{}
}

// MockcatalogListMockRecorder is the mock recorder for MockcatalogList.
type MockcatalogListMockRecorder struct {
	mock *MockcatalogList
}

// NewMockcatalogList creates a new mock instance.
func NewMockcatalogList(ctrl *gomock.Controller) *MockcatalogList {
	mock := &MockcatalogList{ctrl: ctrl}
	mock.recorder = &MockcatalogListMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockcatalogList) EXPECT() *MockcatalogListMockRecorder {
	return m.recorder
}

// Handle mocks base method.
func (m *MockcatalogList) Handle(ctx context.Context, u *model.User, in dto.Input) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Handle", ctx, u, in)
	ret0, _ := ret[0].(error)
	return ret0
}

// Handle indicates an expected call of Handle.
func (mr *MockcatalogListMockRecorder) Handle(ctx, u, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Handle", reflect.TypeOf((*MockcatalogList)(nil).Handle), ctx, u, in)
}

// MockcatalogInfo is a mock of catalogInfo interface.
type MockcatalogInfo struct {
	ctrl     *gomock.Controller
	recorder *MockcatalogInfoMockRecorder
	isgomock struct{}
}

// MockcatalogInfoMockRecorder is the mock recorder for MockcatalogInfo.
type MockcatalogInfoMockRecorder struct {
	mock *MockcatalogInfo
}

// NewMockcatalogInfo creates a new mock instance.
func NewMockcatalogInfo(ctrl *gomock.Controller) *MockcatalogInfo {
	mock := &MockcatalogInfo{ctrl: ctrl}
	mock.recorder = &MockcatalogInfoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockcatalogInfo) EXPECT() *MockcatalogInfoMockRecorder {
	return m.recorder
}

// Handle mocks base method.
func (m *MockcatalogInfo) Handle(ctx context.Context, u *model.User, in dto.Input) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Handle", ctx, u, in)
	ret0, _ := ret[0].(error)
	return ret0
}

// Handle indicates an expected call of Handle.
func (mr *MockcatalogInfoMockRecorder) Handle(ctx, u, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Handle", reflect.TypeOf((*MockcatalogInfo)(nil).Handle), ctx, u, in)
}

// MockcatalogAdd is a mock of catalogAdd interface.
type MockcatalogAdd struct {
	ctrl     *gomock.Controller
	recorder *MockcatalogAddMockRecorder
	isgomock struct{}
}

// MockcatalogAddMockRecorder is the mock recorder for MockcatalogAdd.
type MockcatalogAddMockRecorder struct {
	mock *MockcatalogAdd
}

// NewMockcatalogAdd creates a new mock instance.
func NewMockcatalogAdd(ctrl *gomock.Controller) *MockcatalogAdd {
	mock := &MockcatalogAdd{ctrl: ctrl}
	mock.recorder = &MockcatalogAddMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockcatalogAdd) EXPECT() *MockcatalogAddMockRecorder {
	return m.recorder
}

// Handle mocks base method.
func (m *MockcatalogAdd) Handle(ctx context.Context, u *model.User, in dto.Input) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Handle", ctx, u, in)
	ret0, _ := ret[0].(error)
	return ret0
}

// Handle indicates an expected call of Handle.
func (mr *MockcatalogAddMockRecorder) Handle(ctx, u, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Handle", reflect.TypeOf((*MockcatalogAdd)(nil).Handle), ctx, u, in)
}
