// Code generated by MockGen. DO NOT EDIT.
// Source: contract.go
//
// Generated by this command:
//
//	mockgen -source=contract.go -destination=mock_update_test.go -package=update_test
//

// Package update_test is a generated GoMock package.
package update_test

import (
	context "context"
	reflect "reflect"

	model "github.com/khambek-archakov/jitLog/internal/model"
	dto "github.com/khambek-archakov/jitLog/internal/usecase/dto"
	gomock "go.uber.org/mock/gomock"
)

// Mocksender is a mock of sender interface.
type Mocksender struct {
	ctrl     *gomock.Controller
	recorder *MocksenderMockRecorder
	isgomock struct{}
}

// MocksenderMockRecorder is the mock recorder for Mocksender.
type MocksenderMockRecorder struct {
	mock *Mocksender
}

// NewMocksender creates a new mock instance.
func NewMocksender(ctrl *gomock.Controller) *Mocksender {
	mock := &Mocksender{ctrl: ctrl}
	mock.recorder = &MocksenderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mocksender) EXPECT() *MocksenderMockRecorder {
	return m.recorder
}

// AnswerCallback mocks base method.
func (m *Mocksender) AnswerCallback(callbackID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AnswerCallback", callbackID)
	ret0, _ := ret[0].(error)
	return ret0
}

// AnswerCallback indicates an expected call of AnswerCallback.
func (mr *MocksenderMockRecorder) AnswerCallback(callbackID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AnswerCallback", reflect.TypeOf((*Mocksender)(nil).AnswerCallback), callbackID)
}

// AnswerCallbackWithText mocks base method.
func (m *Mocksender) AnswerCallbackWithText(callbackID, text string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AnswerCallbackWithText", callbackID, text)
	ret0, _ := ret[0].(error)
	return ret0
}

// AnswerCallbackWithText indicates an expected call of AnswerCallbackWithText.
func (mr *MocksenderMockRecorder) AnswerCallbackWithText(callbackID, text any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AnswerCallbackWithText", reflect.TypeOf((*Mocksender)(nil).AnswerCallbackWithText), callbackID, text)
}

// EditMessageWithKeyboard mocks base method.
func (m *Mocksender) EditMessageWithKeyboard(chatID int64, messageID int, text string, keyboard dto.Keyboard) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EditMessageWithKeyboard", chatID, messageID, text, keyboard)
	ret0, _ := ret[0].(error)
	return ret0
}

// EditMessageWithKeyboard indicates an expected call of EditMessageWithKeyboard.
func (mr *MocksenderMockRecorder) EditMessageWithKeyboard(chatID, messageID, text, keyboard any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EditMessageWithKeyboard", reflect.TypeOf((*Mocksender)(nil).EditMessageWithKeyboard), chatID, messageID, text, keyboard)
}

// Send mocks base method.
func (m *Mocksender) Send(chatID int64, text string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Send", chatID, text)
	ret0, _ := ret[0].(error)
	return ret0
}

// Send indicates an expected call of Send.
func (mr *MocksenderMockRecorder) Send(chatID, text any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Send", reflect.TypeOf((*Mocksender)(nil).Send), chatID, text)
}

// SendWithKeyboard mocks base method.
func (m *Mocksender) SendWithKeyboard(chatID int64, text string, keyboard dto.Keyboard) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendWithKeyboard", chatID, text, keyboard)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendWithKeyboard indicates an expected call of SendWithKeyboard.
func (mr *MocksenderMockRecorder) SendWithKeyboard(chatID, text, keyboard any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendWithKeyboard", reflect.TypeOf((*Mocksender)(nil).SendWithKeyboard), chatID, text, keyboard)
}

// MockslotRepo is a mock of slotRepo interface.
type MockslotRepo struct {
	ctrl     *gomock.Controller
	recorder *MockslotRepoMockRecorder
	isgomock struct{}
}

// MockslotRepoMockRecorder is the mock recorder for MockslotRepo.
type MockslotRepoMockRecorder struct {
	mock *MockslotRepo
}

// NewMockslotRepo creates a new mock instance.
func NewMockslotRepo(ctrl *gomock.Controller) *MockslotRepo {
	mock := &MockslotRepo{ctrl: ctrl}
	mock.recorder = &MockslotRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockslotRepo) EXPECT() *MockslotRepoMockRecorder {
	return m.recorder
}

// DeleteEditDraft mocks base method.
func (m *MockslotRepo) DeleteEditDraft(ctx context.Context, userID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteEditDraft", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteEditDraft indicates an expected call of DeleteEditDraft.
func (mr *MockslotRepoMockRecorder) DeleteEditDraft(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteEditDraft", reflect.TypeOf((*MockslotRepo)(nil).DeleteEditDraft), ctx, userID)
}

// GetSlot mocks base method.
func (m *MockslotRepo) GetSlot(ctx context.Context, id int64) (*model.ScheduleSlot, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSlot", ctx, id)
	ret0, _ := ret[0].(*model.ScheduleSlot)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSlot indicates an expected call of GetSlot.
func (mr *MockslotRepoMockRecorder) GetSlot(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSlot", reflect.TypeOf((*MockslotRepo)(nil).GetSlot), ctx, id)
}

// SetEditDraft mocks base method.
func (m *MockslotRepo) SetEditDraft(ctx context.Context, userID, slotID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetEditDraft", ctx, userID, slotID)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetEditDraft indicates an expected call of SetEditDraft.
func (mr *MockslotRepoMockRecorder) SetEditDraft(ctx, userID, slotID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetEditDraft", reflect.TypeOf((*MockslotRepo)(nil).SetEditDraft), ctx, userID, slotID)
}

// UpdateSlot mocks base method.
func (m *MockslotRepo) UpdateSlot(ctx context.Context, id int64, dayOfWeek, timeMinutes int16, trainingType model.TrainingType) (*model.ScheduleSlot, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateSlot", ctx, id, dayOfWeek, timeMinutes, trainingType)
	ret0, _ := ret[0].(*model.ScheduleSlot)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateSlot indicates an expected call of UpdateSlot.
func (mr *MockslotRepoMockRecorder) UpdateSlot(ctx, id, dayOfWeek, timeMinutes, trainingType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSlot", reflect.TypeOf((*MockslotRepo)(nil).UpdateSlot), ctx, id, dayOfWeek, timeMinutes, trainingType)
}
