// Code generated by MockGen. DO NOT EDIT.
// Source: contract.go
//
// Generated by this command:
//
//	mockgen -source=contract.go -destination=mock_submit_test.go -package=submit_test
//

// Package submit_test is a generated GoMock package.
package submit_test

import (
	context "context"
	reflect "reflect"
	time "time"

	model "github.com/khambek-archakov/jitLog/internal/model"
	dto "github.com/khambek-archakov/jitLog/internal/usecase/dto"
	gomock "go.uber.org/mock/gomock"
)

// Mocksender is a mock of sender interface.
type Mocksender struct {
	ctrl     *gomock.Controller
	recorder *MocksenderMockRecorder
	isgomock struct{}
}

// MocksenderMockRecorder is the mock recorder for Mocksender.
type MocksenderMockRecorder struct {
	mock *Mocksender
}

// NewMocksender creates a new mock instance.
func NewMocksender(ctrl *gomock.Controller) *Mocksender {
	mock := &Mocksender{ctrl: ctrl}
	mock.recorder = &MocksenderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mocksender) EXPECT() *MocksenderMockRecorder {
	return m.recorder
}

// AnswerCallback mocks base method.
func (m *Mocksender) AnswerCallback(ctx context.Context, callbackID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AnswerCallback", ctx, callbackID)
	ret0, _ := ret[0].(error)
	return ret0
}

// AnswerCallback indicates an expected call of AnswerCallback.
func (mr *MocksenderMockRecorder) AnswerCallback(ctx, callbackID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AnswerCallback", reflect.TypeOf((*Mocksender)(nil).AnswerCallback), ctx, callbackID)
}

// AnswerCallbackWithText mocks base method.
func (m *Mocksender) AnswerCallbackWithText(ctx context.Context, callbackID, text string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AnswerCallbackWithText", ctx, callbackID, text)
	ret0, _ := ret[0].(error)
	return ret0
}

// AnswerCallbackWithText indicates an expected call of AnswerCallbackWithText.
func (mr *MocksenderMockRecorder) AnswerCallbackWithText(ctx, callbackID, text any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AnswerCallbackWithText", reflect.TypeOf((*Mocksender)(nil).AnswerCallbackWithText), ctx, callbackID, text)
}

// EditMessageWithKeyboard mocks base method.
func (m *Mocksender) EditMessageWithKeyboard(ctx context.Context, chatID int64, messageID int, text string, keyboard dto.Keyboard) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EditMessageWithKeyboard", ctx, chatID, messageID, text, keyboard)
	ret0, _ := ret[0].(error)
	return ret0
}

// EditMessageWithKeyboard indicates an expected call of EditMessageWithKeyboard.
func (mr *MocksenderMockRecorder) EditMessageWithKeyboard(ctx, chatID, messageID, text, keyboard any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EditMessageWithKeyboard", reflect.TypeOf((*Mocksender)(nil).EditMessageWithKeyboard), ctx, chatID, messageID, text, keyboard)
}

// Send mocks base method.
func (m *Mocksender) Send(ctx context.Context, chatID int64, text string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Send", ctx, chatID, text)
	ret0, _ := ret[0].(error)
	return ret0
}

// Send indicates an expected call of Send.
func (mr *MocksenderMockRecorder) Send(ctx, chatID, text any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Send", reflect.TypeOf((*Mocksender)(nil).Send), ctx, chatID, text)
}

// SendWithKeyboard mocks base method.
func (m *Mocksender) SendWithKeyboard(ctx context.Context, chatID int64, text string, keyboard dto.Keyboard) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendWithKeyboard", ctx, chatID, text, keyboard)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendWithKeyboard indicates an expected call of SendWithKeyboard.
func (mr *MocksenderMockRecorder) SendWithKeyboard(ctx, chatID, text, keyboard any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendWithKeyboard", reflect.TypeOf((*Mocksender)(nil).SendWithKeyboard), ctx, chatID, text, keyboard)
}

// Mockrepo is a mock of repo interface.
type Mockrepo struct {
	ctrl     *gomock.Controller
	recorder *MockrepoMockRecorder
	isgomock struct{}
}

// MockrepoMockRecorder is the mock recorder for Mockrepo.
type MockrepoMockRecorder struct {
	mock *Mockrepo
}

// NewMockrepo creates a new mock instance.
func NewMockrepo(ctrl *gomock.Controller) *Mockrepo {
	mock := &Mockrepo{ctrl: ctrl}
	mock.recorder = &MockrepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mockrepo) EXPECT() *MockrepoMockRecorder {
	return m.recorder
}

// AddCompetitionSource mocks base method.
func (m *Mockrepo) AddCompetitionSource(ctx context.Context, competitionID int64, url string, isPrimary bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddCompetitionSource", ctx, competitionID, url, isPrimary)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddCompetitionSource indicates an expected call of AddCompetitionSource.
func (mr *MockrepoMockRecorder) AddCompetitionSource(ctx, competitionID, url, isPrimary any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddCompetitionSource", reflect.TypeOf((*Mockrepo)(nil).AddCompetitionSource), ctx, competitionID, url, isPrimary)
}

// CreateCompetition mocks base method.
func (m *Mockrepo) CreateCompetition(ctx context.Context, title string, date time.Time, endDate *time.Time, city *string, createdBy int64) (*model.Competition, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateCompetition", ctx, title, date, endDate, city, createdBy)
	ret0, _ := ret[0].(*model.Competition)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateCompetition indicates an expected call of CreateCompetition.
func (mr *MockrepoMockRecorder) CreateCompetition(ctx, title, date, endDate, city, createdBy any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateCompetition", reflect.TypeOf((*Mockrepo)(nil).CreateCompetition), ctx, title, date, endDate, city, createdBy)
}

// FindCandidates mocks base method.
func (m *Mockrepo) FindCandidates(ctx context.Context, date time.Time, city string) ([]*model.Competition, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindCandidates", ctx, date, city)
	ret0, _ := ret[0].([]*model.Competition)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindCandidates indicates an expected call of FindCandidates.
func (mr *MockrepoMockRecorder) FindCandidates(ctx, date, city any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindCandidates", reflect.TypeOf((*Mockrepo)(nil).FindCandidates), ctx, date, city)
}

// FindSourceByURL mocks base method.
func (m *Mockrepo) FindSourceByURL(ctx context.Context, url string) (*model.CompetitionSource, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindSourceByURL", ctx, url)
	ret0, _ := ret[0].(*model.CompetitionSource)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindSourceByURL indicates an expected call of FindSourceByURL.
func (mr *MockrepoMockRecorder) FindSourceByURL(ctx, url any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindSourceByURL", reflect.TypeOf((*Mockrepo)(nil).FindSourceByURL), ctx, url)
}

// GetUserCompetition mocks base method.
func (m *Mockrepo) GetUserCompetition(ctx context.Context, id int64) (*model.UserCompetition, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserCompetition", ctx, id)
	ret0, _ := ret[0].(*model.UserCompetition)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserCompetition indicates an expected call of GetUserCompetition.
func (mr *MockrepoMockRecorder) GetUserCompetition(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserCompetition", reflect.TypeOf((*Mockrepo)(nil).GetUserCompetition), ctx, id)
}

// LinkUserCompetition mocks base method.
func (m *Mockrepo) LinkUserCompetition(ctx context.Context, userCompetitionID, competitionID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LinkUserCompetition", ctx, userCompetitionID, competitionID)
	ret0, _ := ret[0].(error)
	return ret0
}

// LinkUserCompetition indicates an expected call of LinkUserCompetition.
func (mr *MockrepoMockRecorder) LinkUserCompetition(ctx, userCompetitionID, competitionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LinkUserCompetition", reflect.TypeOf((*Mockrepo)(nil).LinkUserCompetition), ctx, userCompetitionID, competitionID)
}
