// Code generated by MockGen. DO NOT EDIT.
// Source: contract.go
//
// Generated by this command:
//
//	mockgen -source=contract.go -destination=mock_steps_test.go -package=steps_test
//

// Package steps_test is a generated GoMock package.
package steps_test

import (
	context "context"
	reflect "reflect"

	model "github.com/khambek-archakov/jitLog/internal/model"
	dto "github.com/khambek-archakov/jitLog/internal/usecase/start/dto"
	gomock "go.uber.org/mock/gomock"
)

// Mocksender is a mock of sender interface.
type Mocksender struct {
	ctrl     *gomock.Controller
	recorder *MocksenderMockRecorder
	isgomock struct{}
}

// MocksenderMockRecorder is the mock recorder for Mocksender.
type MocksenderMockRecorder struct {
	mock *Mocksender
}

// NewMocksender creates a new mock instance.
func NewMocksender(ctrl *gomock.Controller) *Mocksender {
	mock := &Mocksender{ctrl: ctrl}
	mock.recorder = &MocksenderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mocksender) EXPECT() *MocksenderMockRecorder {
	return m.recorder
}

// AnswerCallback mocks base method.
func (m *Mocksender) AnswerCallback(callbackID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AnswerCallback", callbackID)
	ret0, _ := ret[0].(error)
	return ret0
}

// AnswerCallback indicates an expected call of AnswerCallback.
func (mr *MocksenderMockRecorder) AnswerCallback(callbackID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AnswerCallback", reflect.TypeOf((*Mocksender)(nil).AnswerCallback), callbackID)
}

// AnswerCallbackWithText mocks base method.
func (m *Mocksender) AnswerCallbackWithText(callbackID, text string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AnswerCallbackWithText", callbackID, text)
	ret0, _ := ret[0].(error)
	return ret0
}

// AnswerCallbackWithText indicates an expected call of AnswerCallbackWithText.
func (mr *MocksenderMockRecorder) AnswerCallbackWithText(callbackID, text any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AnswerCallbackWithText", reflect.TypeOf((*Mocksender)(nil).AnswerCallbackWithText), callbackID, text)
}

// Send mocks base method.
func (m *Mocksender) Send(chatID int64, text string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Send", chatID, text)
	ret0, _ := ret[0].(error)
	return ret0
}

// Send indicates an expected call of Send.
func (mr *MocksenderMockRecorder) Send(chatID, text any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Send", reflect.TypeOf((*Mocksender)(nil).Send), chatID, text)
}

// SendWithKeyboard mocks base method.
func (m *Mocksender) SendWithKeyboard(chatID int64, text string, keyboard dto.Keyboard) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendWithKeyboard", chatID, text, keyboard)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendWithKeyboard indicates an expected call of SendWithKeyboard.
func (mr *MocksenderMockRecorder) SendWithKeyboard(chatID, text, keyboard any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendWithKeyboard", reflect.TypeOf((*Mocksender)(nil).SendWithKeyboard), chatID, text, keyboard)
}

// Mockuser is a mock of user interface.
type Mockuser struct {
	ctrl     *gomock.Controller
	recorder *MockuserMockRecorder
	isgomock struct{}
}

// MockuserMockRecorder is the mock recorder for Mockuser.
type MockuserMockRecorder struct {
	mock *Mockuser
}

// NewMockuser creates a new mock instance.
func NewMockuser(ctrl *gomock.Controller) *Mockuser {
	mock := &Mockuser{ctrl: ctrl}
	mock.recorder = &MockuserMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mockuser) EXPECT() *MockuserMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *Mockuser) Create(ctx context.Context, telegramID int64) (*model.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, telegramID)
	ret0, _ := ret[0].(*model.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockuserMockRecorder) Create(ctx, telegramID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*Mockuser)(nil).Create), ctx, telegramID)
}

// GetByTelegramID mocks base method.
func (m *Mockuser) GetByTelegramID(ctx context.Context, telegramID int64) (*model.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByTelegramID", ctx, telegramID)
	ret0, _ := ret[0].(*model.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByTelegramID indicates an expected call of GetByTelegramID.
func (mr *MockuserMockRecorder) GetByTelegramID(ctx, telegramID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByTelegramID", reflect.TypeOf((*Mockuser)(nil).GetByTelegramID), ctx, telegramID)
}

// Update mocks base method.
func (m *Mockuser) Update(ctx context.Context, u *model.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, u)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockuserMockRecorder) Update(ctx, u any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*Mockuser)(nil).Update), ctx, u)
}
